/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nalpeiron_nalplibrary_nalpError */

#ifndef _Included_com_nalpeiron_nalplibrary_nalpError
#define _Included_com_nalpeiron_nalplibrary_nalpError
#ifdef __cplusplus
extern "C" {
#endif
#undef com_nalpeiron_nalplibrary_nalpError_serialVersionUID
#define com_nalpeiron_nalplibrary_nalpError_serialVersionUID -3042686055658047285i64
#undef com_nalpeiron_nalplibrary_nalpError_serialVersionUID
#define com_nalpeiron_nalplibrary_nalpError_serialVersionUID 4980196508277280342i64
#undef com_nalpeiron_nalplibrary_nalpError_serialVersionUID
#define com_nalpeiron_nalplibrary_nalpError_serialVersionUID 999i64
#ifdef __cplusplus
}
#endif
#endif
