/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nalpeiron_nalplibrary_NALP */

#ifndef _Included_com_nalpeiron_nalplibrary_NALP
#define _Included_com_nalpeiron_nalplibrary_NALP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nalpeiron_nalplibrary_NALP
 * Method:    NalpLibOpen
 * Signature: ([B[B[J)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NALP_NalpLibOpen
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jlongArray);

/*
 * Class:     com_nalpeiron_nalplibrary_NALP
 * Method:    NalpLibClose
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NALP_NalpLibClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nalpeiron_nalplibrary_NALP
 * Method:    NalpGetErrorMsg
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nalpeiron_nalplibrary_NALP_NalpGetErrorMsg
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
