/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nalpeiron_nalplibrary_NSL */

#ifndef _Included_com_nalpeiron_nalplibrary_NSL
#define _Included_com_nalpeiron_nalplibrary_NSL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLValidateLibrary
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLValidateLibrary
  (JNIEnv *, jobject, jlong, jlong, jlong, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLGetVersion
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLGetVersion
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLGetComputerID
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLGetComputerID
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLGetHostName
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLGetHostName
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLGetLeaseExpDate
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLGetLeaseExpDate
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLGetLeaseExpSec
 * Signature: (J[I[II)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLGetLeaseExpSec
  (JNIEnv *, jobject, jlong, jintArray, jintArray, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLGetRefreshExpDate
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLGetRefreshExpDate
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLGetRefreshExpSec
 * Signature: (J[I[II)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLGetRefreshExpSec
  (JNIEnv *, jobject, jlong, jintArray, jintArray, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLGetSubExpDate
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLGetSubExpDate
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLGetSubExpSec
 * Signature: (J[I[II)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLGetSubExpSec
  (JNIEnv *, jobject, jlong, jintArray, jintArray, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLGetMaintExpDate
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLGetMaintExpDate
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLGetMaintExpSec
 * Signature: (J[I[II)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLGetMaintExpSec
  (JNIEnv *, jobject, jlong, jintArray, jintArray, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLGetTrialExpDate
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLGetTrialExpDate
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLGetTrialExpSec
 * Signature: (J[I[II)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLGetTrialExpSec
  (JNIEnv *, jobject, jlong, jintArray, jintArray, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLGetLicenseCode
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLGetLicenseCode
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLGetLicenseStatus
 * Signature: (J[II)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLGetLicenseStatus
  (JNIEnv *, jobject, jlong, jintArray, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLGetLicenseInfo
 * Signature: (J[I[II)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLGetLicenseInfo
  (JNIEnv *, jobject, jlong, jintArray, jintArray, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLGetNumbAvailProc
 * Signature: (J[I[II)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLGetNumbAvailProc
  (JNIEnv *, jobject, jlong, jintArray, jintArray, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLGetTimeStamp
 * Signature: (J[II)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLGetTimeStamp
  (JNIEnv *, jobject, jlong, jintArray, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLGetFeatureStatus
 * Signature: (J[B[II)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLGetFeatureStatus
  (JNIEnv *, jobject, jlong, jbyteArray, jintArray, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLCheckoutFeature
 * Signature: (J[B[B[II)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLCheckoutFeature
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jintArray, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLReturnFeature
 * Signature: (J[B[BI)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLReturnFeature
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLGetPoolStatus
 * Signature: (J[B[I[II)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLGetPoolStatus
  (JNIEnv *, jobject, jlong, jbyteArray, jintArray, jintArray, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLCheckoutPool
 * Signature: (J[B[BI[II)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLCheckoutPool
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jint, jintArray, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLReturnPool
 * Signature: (J[B[BII)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLReturnPool
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLGetLicense
 * Signature: (J[B[B[II)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLGetLicense
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jintArray, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLReturnLicense
 * Signature: (J[B[II)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLReturnLicense
  (JNIEnv *, jobject, jlong, jbyteArray, jintArray, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLImportCertificate
 * Signature: (J[B[B[II)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLImportCertificate
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jintArray, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLGetActivationCertReq
 * Signature: (J[B[B[BI)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLGetActivationCertReq
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLGetDeactivationCertReq
 * Signature: (J[B[BI)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLGetDeactivationCertReq
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLGetUDFValue
 * Signature: (J[B[BI)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLGetUDFValue
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLRegister
 * Signature: (J[B[BI)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLRegister
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLTestConnection
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLTestConnection
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLGetNewLicenseCode
 * Signature: (J[B[BI)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLGetNewLicenseCode
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLGetPreset
 * Signature: (JI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLGetPreset
  (JNIEnv *, jobject, jlong, jint, jbyteArray, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSL
 * Method:    NSLGetMsgByDate
 * Signature: (J[I[BI)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_nalpeiron_nalplibrary_NSL_NSLGetMsgByDate
  (JNIEnv *, jobject, jlong, jintArray, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
