package com.docshifter.core.utils;

import lombok.Synchronized;
import org.apache.commons.collections.BidiMap;
import org.apache.commons.collections.bidimap.DualHashBidiMap;

public class MimeMapper {
	private static MimeMapper instance;
    private static BidiMap biMap;
    public MimeMapper() {
        biMap = new DualHashBidiMap();
		addEntry("3D Crossword Plugin", "application/vnd.hzn-3d-crossword", "x3d", "IANA: 3D Crossword Plugin");
		addEntry("3GP", "video/3gpp", "3gp", "Wikipedia: 3GP");
		addEntry("3GP2", "video/3gpp2", "3g2", "Wikipedia: 3G2");
		addEntry("3GPP MSEQ File", "application/vnd.mseq", "mseq", "IANA: 3GPP MSEQ File");
		addEntry("3M Post It Notes", "application/vnd.3m.post-it-notes", "pwn", "IANA: 3M Post It Notes");
		addEntry("3rd Generation Partnership Project - Pic Large", "application/vnd.3gpp.pic-bw-large", "plb", "3GPP");
		addEntry("3rd Generation Partnership Project - Pic Small", "application/vnd.3gpp.pic-bw-small", "psb", "3GPP");
		addEntry("3rd Generation Partnership Project - Pic Var", "application/vnd.3gpp.pic-bw-var", "pvb", "3GPP");
		addEntry("3rd Generation Partnership Project - Transaction Capabilities Application Part", "application/vnd.3gpp2.tcap", "tcap", "3GPP");
		addEntry("7-Zip", "application/x-7z-compressed", "7z", "Wikipedia: 7-Zip");
		addEntry("AbiWord", "application/x-abiword", "abw", "Wikipedia: AbiWord");
		addEntry("Ace Archive", "application/x-ace-compressed", "ace", "Wikipedia: ACE");
		addEntry("Active Content Compression", "application/vnd.americandynamics.acc", "acc", "IANA: Active Content Compression");
		addEntry("ACU Cobol", "application/vnd.acucobol", "acu", "IANA: ACU Cobol");
		addEntry("ACU Cobol", "application/vnd.acucorp", "atc", "IANA: ACU Cobol");
		addEntry("Adaptive differential pulse-code modulation", "audio/adpcm", "adp", "Wikipedia: ADPCM");
		addEntry("Adobe (Macropedia) Authorware - Binary File", "application/x-authorware-bin", "aab", "Wikipedia: Authorware");
		addEntry("Adobe (Macropedia) Authorware - Map", "application/x-authorware-map", "aam", "Wikipedia: Authorware");
		addEntry("Adobe (Macropedia) Authorware - Segment File", "application/x-authorware-seg", "aas", "Wikipedia: Authorware");
		addEntry("Adobe AIR Application", "application/vnd.adobe.air-application-installer-package+zip", "air", "Building AIR Applications");
		addEntry("Adobe Flash", "application/x-shockwave-flash", "swf", "Wikipedia: Adobe Flash");
		addEntry("Adobe Flex Project", "application/vnd.adobe.fxp", "fxp", "IANA: Adobe Flex Project");
		addEntry("Adobe Portable Document Format", "application/pdf", "pdf", "Adobe PDF");
		addEntry("Adobe PostScript Printer Description File Format", "application/vnd.cups-ppd", "ppd", "IANA: Cups");
		addEntry("Adobe Shockwave Player", "application/x-director", "dir", "Wikipedia: Adobe Shockwave Player");
		addEntry("Adobe XML Data Package", "application/vnd.adobe.xdp+xml", "xdp", "Wikipedia: XML Data Package");
		addEntry("Adobe XML Forms Data Format", "application/vnd.adobe.xfdf", "xfdf", "Wikipedia: XML Portable Document Format");
		addEntry("Advanced Audio Coding (AAC)", "audio/x-aac", "aac", "Wikipedia: AAC");
		addEntry("Ahead AIR Application", "application/vnd.ahead.space", "ahead", "IANA: Ahead AIR Application");
		addEntry("AirZip FileSECURE", "application/vnd.airzip.filesecure.azf", "azf", "IANA: AirZip");
		addEntry("AirZip FileSECURE", "application/vnd.airzip.filesecure.azs", "azs", "IANA: AirZip");
		addEntry("Amazon Kindle eBook format", "application/vnd.amazon.ebook", "azw", "Kindle Direct Publishing");
		addEntry("AmigaDE", "application/vnd.amiga.ami", "ami", "IANA: Amiga");
		addEntry("Andrew Toolkit", "application/andrew-inset", "N/A", "IANA - Andrew Inset");
		addEntry("Android Package Archive", "application/vnd.android.package-archive", "apk", "Wikipedia: APK File Format");
		addEntry("ANSER-WEB Terminal Client - Certificate Issue", "application/vnd.anser-web-certificate-issue-initiation", "cii", "IANA: ANSWER-WEB");
		addEntry("ANSER-WEB Terminal Client - Web Funds Transfer", "application/vnd.anser-web-funds-transfer-initiation", "fti", "IANA: ANSWER-WEB");
		addEntry("Antix Game Player", "application/vnd.antix.game-component", "atx", "IANA: Antix Game Component");
		addEntry("Apple Disk Image", "application/x-apple-diskimage", "dmg", "Apple Disk Image");
		addEntry("Apple Installer Package", "application/vnd.apple.installer+xml", "mpkg", "IANA: Apple Installer");
		addEntry("Applixware", "application/applixware", "aw", "Vistasource");
		addEntry("Archipelago Lesson Player", "application/vnd.hhe.lesson-player", "les", "IANA: Archipelago Lesson Player");
		addEntry("Archive document - Multiple Fils Embedded", "application/x-freearc", "arc", "FreeArc");
		addEntry("Arista Networks Software Image", "application/vnd.aristanetworks.swi", "swi", "IANA: Arista Networks Software Image");
		addEntry("Assembler Source File", "text/x-asm", "s", "Wikipedia: Assembly");
		addEntry("Atom Publishing Protocol", "application/atomcat+xml", "atomcat", "RFC 5023");
		addEntry("Atom Publishing Protocol Service Document", "application/atomsvc+xml", "atomsvc", "RFC 5023");
		addEntry("Atom Syndication Format", "application/atom+xml", "atom, xml", "RFC 4287");
		addEntry("Attribute Certificate", "application/pkix-attr-cert", "ac", "RFC 5877");
		addEntry("Audio Interchange File Format", "audio/x-aiff", "aif", "Wikipedia: Audio Interchange File Format");
		addEntry("Audio Video Interleave (AVI)", "video/x-msvideo", "avi", "Wikipedia: AVI");
		addEntry("Audiograph", "application/vnd.audiograph", "aep", "IANA: Audiograph");
		addEntry("AutoCAD DXF", "image/vnd.dxf", "dxf", "Wikipedia: AutoCAD DXF");
		addEntry("Autodesk Design Web Format (DWF)", "model/vnd.dwf", "dwf", "Wikipedia: Design Web Format");
		addEntry("AV1 Image File", "image/avif", "avif", "AV1 Image File Format");
		addEntry("BAS Partitur Format", "text/plain-bas", "par", "Phonetik BAS");
		addEntry("Binary CPIO Archive", "application/x-bcpio", "bcpio", "Wikipedia: cpio");
		addEntry("Binary Data", "application/octet-stream", "bin", "");
		addEntry("Bitmap Image File", "image/bmp", "bmp", "Wikipedia: BMP File Format");
		addEntry("BitTorrent", "application/x-bittorrent", "torrent", "Wikipedia: BitTorrent");
		addEntry("Blackberry COD File", "application/vnd.rim.cod", "cod", "");
		addEntry("Blueice Research Multipass", "application/vnd.blueice.multipass", "mpm", "IANA: Multipass");
		addEntry("BMI Drawing Data Interchange", "application/vnd.bmi", "bmi", "IANA: BMI");
		addEntry("Bourne Shell Script", "application/x-sh", "sh", "Wikipedia: Bourne Shell");
		addEntry("BTIF", "image/prs.btif", "btif", "IANA: BTIF");
		addEntry("BusinessObjects", "application/vnd.businessobjects", "rep", "IANA: BusinessObjects");
		addEntry("Bzip Archive", "application/x-bzip", "bz", "Wikipedia: Bzip");
		addEntry("Bzip2 Archive", "application/x-bzip2", "bz2", "Wikipedia: Bzip");
		addEntry("C Shell Script", "application/x-csh", "csh", "Wikipedia: C Shell");
		addEntry("C Source File", "text/x-c", "c", "Wikipedia: C Programming Language");
		addEntry("CambridgeSoft Chem Draw", "application/vnd.chemdraw+xml", "cdxml", "IANA: Chem Draw");
		addEntry("Cascading Style Sheets (CSS)", "text/css", "css", "Wikipedia: CSS");
		addEntry("CD Audio", "application/x-cdf", "cda", "Wikipedia: CDA File");
		addEntry("ChemDraw eXchange file", "chemical/x-cdx", "cdx", "ChemDraw eXchange file");
		addEntry("Chemical Markup Language", "chemical/x-cml", "cml", "Wikipedia: Chemical Markup Language");
		addEntry("Chemical Style Markup Language", "chemical/x-csml", "csml", "Wikipedia: Chemical Style Markup Language");
		addEntry("CIM Database", "application/vnd.contact.cmsg", "cdbcmsg", "IANA: CIM Database");
		addEntry("Claymore Data Files", "application/vnd.claymore", "cla", "IANA: Claymore");
		addEntry("Clonk Game", "application/vnd.clonk.c4group", "c4g", "IANA: Clonk");
		addEntry("Close Captioning - Subtitle", "image/vnd.dvb.subtitle", "sub", "Wikipedia: Closed Captioning");
		addEntry("Cloud Data Management Interface (CDMI) - Capability", "application/cdmi-capability", "cdmia", "RFC 6208");
		addEntry("Cloud Data Management Interface (CDMI) - Contaimer", "application/cdmi-container", "cdmic", "RFC 6209");
		addEntry("Cloud Data Management Interface (CDMI) - Domain", "application/cdmi-domain", "cdmid", "RFC 6210");
		addEntry("Cloud Data Management Interface (CDMI) - Object", "application/cdmi-object", "cdmio", "RFC 6211");
		addEntry("Cloud Data Management Interface (CDMI) - Queue", "application/cdmi-queue", "cdmiq", "RFC 6212");
		addEntry("ClueTrust CartoMobile - Config", "application/vnd.cluetrust.cartomobile-config", "c11amc", "IANA: CartoMobile");
		addEntry("ClueTrust CartoMobile - Config Package", "application/vnd.cluetrust.cartomobile-config-pkg", "c11amz", "IANA: CartoMobile");
		addEntry("CMU Image", "image/x-cmu-raster", "ras", "");
		addEntry("COLLADA", "model/vnd.collada+xml", "dae", "IANA: COLLADA");
		addEntry("Comma-Seperated Values", "text/csv", "csv", "Wikipedia: CSV");
		addEntry("Compact Pro", "application/mac-compactpro", "cpt", "Compact Pro");
		addEntry("Compiled Wireless Markup Language (WMLC)", "application/vnd.wap.wmlc", "wmlc", "IANA: WMLC");
		addEntry("Computer Graphics Metafile", "image/cgm", "cgm", "Wikipedia: Computer Graphics Metafile");
		addEntry("CoolTalk", "x-conference/x-cooltalk", "ice", "Wikipedia: CoolTalk");
		addEntry("Corel Metafile Exchange (CMX)", "image/x-cmx", "cmx", "Wikipedia: CorelDRAW");
		addEntry("CorelXARA", "application/vnd.xara", "xar", "IANA: CorelXARA");
		addEntry("CosmoCaller", "application/vnd.cosmocaller", "cmc", "IANA: CosmoCaller");
		addEntry("CPIO Archive", "application/x-cpio", "cpio", "Wikipedia: cpio");
		addEntry("CrickSoftware - Clicker", "application/vnd.crick.clicker", "clkx", "IANA: Clicker");
		addEntry("CrickSoftware - Clicker - Keyboard", "application/vnd.crick.clicker.keyboard", "clkk", "IANA: Clicker");
		addEntry("CrickSoftware - Clicker - Palette", "application/vnd.crick.clicker.palette", "clkp", "IANA: Clicker");
		addEntry("CrickSoftware - Clicker - Template", "application/vnd.crick.clicker.template", "clkt", "IANA: Clicker");
		addEntry("CrickSoftware - Clicker - Wordbank", "application/vnd.crick.clicker.wordbank", "clkw", "IANA: Clicker");
		addEntry("Critical Tools - PERT Chart EXPERT", "application/vnd.criticaltools.wbs+xml", "wbs", "IANA: Critical Tools");
		addEntry("CryptoNote", "application/vnd.rig.cryptonote", "cryptonote", "IANA: CryptoNote");
		addEntry("Crystallographic Interchange Format", "chemical/x-cif", "cif", "Crystallographic Interchange Format");
		addEntry("CrystalMaker Data Format", "chemical/x-cmdf", "cmdf", "CrystalMaker Data Format");
		addEntry("CU-SeeMe", "application/cu-seeme", "cu", "White Pine");
		addEntry("CU-Writer", "application/prs.cww", "cww", "");
		addEntry("Curl - Applet", "text/vnd.curl", "curl", "Curl Applet");
		addEntry("Curl - Detached Applet", "text/vnd.curl.dcurl", "dcurl", "Curl Detached Applet");
		addEntry("Curl - Manifest File", "text/vnd.curl.mcurl", "mcurl", "Curl Manifest File");
		addEntry("Curl - Source Code", "text/vnd.curl.scurl", "scurl", "Curl Source Code");
		addEntry("CURL Applet", "application/vnd.curl.car", "car", "IANA: CURL Applet");
		addEntry("CURL Applet", "application/vnd.curl.pcurl", "pcurl", "IANA: CURL Applet");
		addEntry("CustomMenu", "application/vnd.yellowriver-custom-menu", "cmp", "IANA: CustomMenu");
		addEntry("Data Structure for the Security Suitability of Cryptographic Algorithms", "application/dssc+der", "dssc", "RFC 5698");
		addEntry("Data Structure for the Security Suitability of Cryptographic Algorithms", "application/dssc+xml", "xdssc", "RFC 5698");
		addEntry("Debian Package", "application/x-debian-package", "deb", "Wikipedia: Debian Package");
		addEntry("DECE Audio", "audio/vnd.dece.audio", "uva", "IANA: Dece Audio");
		addEntry("DECE Graphic", "image/vnd.dece.graphic", "uvi", "IANA: DECE Graphic");
		addEntry("DECE High Definition Video", "video/vnd.dece.hd", "uvh", "IANA: DECE HD Video");
		addEntry("DECE Mobile Video", "video/vnd.dece.mobile", "uvm", "IANA: DECE Mobile Video");
		addEntry("DECE MP4", "video/vnd.uvvu.mp4", "uvu", "IANA: DECE MP4");
		addEntry("DECE PD Video", "video/vnd.dece.pd", "uvp", "IANA: DECE PD Video");
		addEntry("DECE SD Video", "video/vnd.dece.sd", "uvs", "IANA: DECE SD Video");
		addEntry("DECE Video", "video/vnd.dece.video", "uvv", "IANA: DECE Video");
		addEntry("Device Independent File Format (DVI)", "application/x-dvi", "dvi", "Wikipedia: DVI");
		addEntry("Digital Siesmograph Networks - SEED Datafiles", "application/vnd.fdsn.seed", "seed", "IANA: SEED");
		addEntry("Digital Talking Book", "application/x-dtbook+xml", "dtb", "Wikipedia: EPUB");
		addEntry("Digital Talking Book - Resource File", "application/x-dtbresource+xml", "res", "Digital Talking Book");
		addEntry("Digital Video Broadcasting", "application/vnd.dvb.ait", "ait", "IANA: Digital Video Broadcasting");
		addEntry("Digital Video Broadcasting", "application/vnd.dvb.service", "svc", "IANA: Digital Video Broadcasting");
		addEntry("Digital Winds Music", "audio/vnd.digital-winds", "eol", "IANA: Digital Winds");
		addEntry("DjVu", "image/vnd.djvu", "djvu", "Wikipedia: DjVu");
		addEntry("Document Type Definition", "application/xml-dtd", "dtd", "W3C DTD");
		addEntry("Dolby Meridian Lossless Packing", "application/vnd.dolby.mlp", "mlp", "IANA: Dolby Meridian Lossless Packing");
		addEntry("Doom Video Game", "application/x-doom", "wad", "Wikipedia: Doom WAD");
		addEntry("DPGraph", "application/vnd.dpgraph", "dpg", "IANA: DPGraph");
		addEntry("DRA Audio", "audio/vnd.dra", "dra", "IANA: DRA");
		addEntry("DreamFactory", "application/vnd.dreamfactory", "dfac", "IANA: DreamFactory");
		addEntry("DTS Audio", "audio/vnd.dts", "dts", "IANA: DTS");
		addEntry("DTS High Definition Audio", "audio/vnd.dts.hd", "dtshd", "IANA: DTS HD");
		addEntry("DWG Drawing", "image/vnd.dwg", "dwg", "Wikipedia: DWG");
		addEntry("DynaGeo", "application/vnd.dynageo", "geo", "IANA: DynaGeo");
		addEntry("ECMAScript", "application/ecmascript", "es", "ECMA-357");
		addEntry("EcoWin Chart", "application/vnd.ecowin.chart", "mag", "IANA: EcoWin Chart");
		addEntry("EDMICS 2000", "image/vnd.fujixerox.edmics-mmr", "mmr", "IANA: EDMICS 2000");
		addEntry("EDMICS 2000", "image/vnd.fujixerox.edmics-rlc", "rlc", "IANA: EDMICS 2000");
		addEntry("Efficient XML Interchange", "application/exi", "exi", "Efficient XML Interchange (EXI) Best Practices");
		addEntry("EFI Proteus", "application/vnd.proteus.magazine", "mgz", "IANA: EFI Proteus");
		addEntry("Electronic Publication", "application/epub+zip", "epub", "Wikipedia: EPUB");
		addEntry("Email Message", "message/rfc822", "eml", "RFC 2822");
		addEntry("Email Message Delivery Status", "message/delivery-status", "txt", "??");
		addEntry("Email Message Headers", "text/rfc822-headers", "txt", "RFC 2822 Headers");
		addEntry("Enliven Viewer", "application/vnd.enliven", "nml", "IANA: Enliven Viewer");
		addEntry("Express by Infoseek", "application/vnd.is-xpr", "xpr", "IANA: Express by Infoseek");
		addEntry("eXtended Image File Format (XIFF)", "image/vnd.xiff", "xif", "IANA: XIFF");
		addEntry("Extensible Forms Description Language", "application/vnd.xfdl", "xfdl", "IANA: Extensible Forms Description Language");
		addEntry("Extensible MultiModal Annotation", "application/emma+xml", "emma", "EMMA: Extensible MultiModal Annotation markup language");
		addEntry("EZPix Secure Photo Album", "application/vnd.ezpix-album", "ez2", "IANA: EZPix Secure Photo Album");
		addEntry("EZPix Secure Photo Album", "application/vnd.ezpix-package", "ez3", "IANA: EZPix Secure Photo Album");
		addEntry("FAST Search & Transfer ASA", "image/vnd.fst", "fst", "IANA: FAST Search & Transfer ASA");
		addEntry("FAST Search & Transfer ASA", "video/vnd.fvt", "fvt", "IANA: FVT");
		addEntry("FastBid Sheet", "image/vnd.fastbidsheet", "fbs", "IANA: FastBid Sheet");
		addEntry("FCS Express Layout Link", "application/vnd.denovo.fcselayout-link", "fe_launch", "IANA: FCS Express Layout Link");
		addEntry("Flash Video", "video/x-f4v", "f4v", "Wikipedia: Flash Video");
		addEntry("Flash Video", "video/x-flv", "flv", "Wikipedia: Flash Video");
		addEntry("FlashPix", "image/vnd.fpx", "fpx", "IANA: FPX");
		addEntry("FlashPix", "image/vnd.net-fpx", "npx", "IANA: FPX");
		addEntry("FLEXSTOR", "text/vnd.fmi.flexstor", "flx", "IANA: FLEXSTOR");
		addEntry("FLI/FLC Animation Format", "video/x-fli", "fli", "FLI/FLC Animation Format");
		addEntry("FluxTime Clip", "application/vnd.fluxtime.clip", "ftc", "IANA: FluxTime Clip");
		addEntry("Forms Data Format", "application/vnd.fdf", "fdf", "IANA: Forms Data Format");
		addEntry("Fortran Source File", "text/x-fortran", "f", "Wikipedia: Fortran");
		addEntry("FrameMaker Interchange Format", "application/vnd.mif", "mif", "IANA: FrameMaker Interchange Format");
		addEntry("FrameMaker Normal Format", "application/vnd.framemaker", "fm", "IANA: FrameMaker");
		addEntry("FreeHand MX", "image/x-freehand", "fh", "Wikipedia: Macromedia Freehand");
		addEntry("Friendly Software Corporation", "application/vnd.fsc.weblaunch", "fsc", "IANA: Friendly Software Corporation");
		addEntry("Frogans Player", "application/vnd.frogans.fnc", "fnc", "IANA: Frogans Player");
		addEntry("Frogans Player", "application/vnd.frogans.ltf", "ltf", "IANA: Frogans Player");
		addEntry("Fujitsu - Xerox 2D CAD Data", "application/vnd.fujixerox.ddd", "ddd", "IANA: Fujitsu DDD");
		addEntry("Fujitsu - Xerox DocuWorks", "application/vnd.fujixerox.docuworks", "xdw", "IANA: Docuworks");
		addEntry("Fujitsu - Xerox DocuWorks Binder", "application/vnd.fujixerox.docuworks.binder", "xbd", "IANA: Docuworks Binder");
		addEntry("Fujitsu Oasys", "application/vnd.fujitsu.oasys", "oas", "IANA: Fujitsu Oasys");
		addEntry("Fujitsu Oasys", "application/vnd.fujitsu.oasys2", "oa2", "IANA: Fujitsu Oasys");
		addEntry("Fujitsu Oasys", "application/vnd.fujitsu.oasys3", "oa3", "IANA: Fujitsu Oasys");
		addEntry("Fujitsu Oasys", "application/vnd.fujitsu.oasysgp", "fg5", "IANA: Fujitsu Oasys");
		addEntry("Fujitsu Oasys", "application/vnd.fujitsu.oasysprs", "bh2", "IANA: Fujitsu Oasys");
		addEntry("FutureSplash Animator", "application/x-futuresplash", "spl", "Wikipedia: FutureSplash Animator");
		addEntry("FuzzySheet", "application/vnd.fuzzysheet", "fzs", "IANA: FuzySheet");
		addEntry("G3 Fax Image", "image/g3fax", "g3", "Wikipedia: G3 Fax Image");
		addEntry("GameMaker ActiveX", "application/vnd.gmx", "gmx", "IANA: GameMaker ActiveX");
		addEntry("Gen-Trix Studio", "model/vnd.gtw", "gtw", "IANA: GTW");
		addEntry("Genomatix Tuxedo Framework", "application/vnd.genomatix.tuxedo", "txd", "IANA: Genomatix Tuxedo Framework");
		addEntry("GeoGebra", "application/vnd.geogebra.file", "ggb", "IANA: GeoGebra");
		addEntry("GeoGebra", "application/vnd.geogebra.tool", "ggt", "IANA: GeoGebra");
		addEntry("Geometric Description Language (GDL)", "model/vnd.gdl", "gdl", "IANA: GDL");
		addEntry("GeoMetry Explorer", "application/vnd.geometry-explorer", "gex", "IANA: GeoMetry Explorer");
		addEntry("GEONExT and JSXGraph", "application/vnd.geonext", "gxt", "IANA: GEONExT and JSXGraph");
		addEntry("GeoplanW", "application/vnd.geoplan", "g2w", "IANA: GeoplanW");
		addEntry("GeospacW", "application/vnd.geospace", "g3w", "IANA: GeospacW");
		addEntry("Ghostscript Font", "application/x-font-ghostscript", "gsf", "Wikipedia: Ghostscript");
		addEntry("Glyph Bitmap Distribution Format", "application/x-font-bdf", "bdf", "Wikipedia: Glyph Bitmap Distribution Format");
		addEntry("GNU Tar Files", "application/x-gtar", "gtar", "GNU Tar");
		addEntry("GNU Texinfo Document", "application/x-texinfo", "texinfo", "Wikipedia: Texinfo");
		addEntry("Gnumeric", "application/x-gnumeric", "gnumeric", "Wikipedia: Gnumeric");
		addEntry("Google Earth - KML", "application/vnd.google-earth.kml+xml", "kml", "IANA: Google Earth");
		addEntry("Google Earth - Zipped KML", "application/vnd.google-earth.kmz", "kmz", "IANA: Google Earth");
		addEntry("GPS eXchange Format", "application/gpx+xml", "gpx", "GPS eXchange Format");
		addEntry("GrafEq", "application/vnd.grafeq", "gqf", "IANA: GrafEq");
		addEntry("Graphics Interchange Format", "image/gif", "gif", "Wikipedia: Graphics Interchange Format");
		addEntry("Graphviz", "text/vnd.graphviz", "gv", "IANA: Graphviz");
		addEntry("Groove - Account", "application/vnd.groove-account", "gac", "IANA: Groove");
		addEntry("Groove - Help", "application/vnd.groove-help", "ghf", "IANA: Groove");
		addEntry("Groove - Identity Message", "application/vnd.groove-identity-message", "gim", "IANA: Groove");
		addEntry("Groove - Injector", "application/vnd.groove-injector", "grv", "IANA: Groove");
		addEntry("Groove - Tool Message", "application/vnd.groove-tool-message", "gtm", "IANA: Groove");
		addEntry("Groove - Tool Template", "application/vnd.groove-tool-template", "tpl", "IANA: Groove");
		addEntry("Groove - Vcard", "application/vnd.groove-vcard", "vcg", "IANA: Groove");
		addEntry("GZip", "application/gzip", "gz", "Wikipedia: GZip");
		addEntry("H.261", "video/h261", "h261", "Wikipedia: H.261");
		addEntry("H.263", "video/h263", "h263", "Wikipedia: H.263");
		addEntry("H.264", "video/h264", "h264", "Wikipedia: H.264");
		addEntry("Hewlett Packard Instant Delivery", "application/vnd.hp-hpid", "hpid", "IANA: Hewlett Packard Instant Delivery");
		addEntry("Hewlett-Packard's WebPrintSmart", "application/vnd.hp-hps", "hps", "IANA: Hewlett-Packard's WebPrintSmart");
		addEntry("Hierarchical Data Format", "application/x-hdf", "hdf", "Wikipedia: Hierarchical Data Format");
		addEntry("Hit'n'Mix", "audio/vnd.rip", "rip", "IANA: Hit'n'Mix");
		addEntry("Homebanking Computer Interface (HBCI)", "application/vnd.hbci", "hbci", "IANA: HBCI");
		addEntry("HP Indigo Digital Press - Job Layout Languate", "application/vnd.hp-jlyt", "jlt", "IANA: HP Job Layout Language");
		addEntry("HP Printer Command Language", "application/vnd.hp-pcl", "pcl", "IANA: HP Printer Command Language");
		addEntry("HP-GL/2 and HP RTL", "application/vnd.hp-hpgl", "hpgl", "IANA: HP-GL/2 and HP RTL");
		addEntry("HV Script", "application/vnd.yamaha.hv-script", "hvs", "IANA: HV Script");
		addEntry("HV Voice Dictionary", "application/vnd.yamaha.hv-dic", "hvd", "IANA: HV Voice Dictionary");
		addEntry("HV Voice Parameter", "application/vnd.yamaha.hv-voice", "hvp", "IANA: HV Voice Parameter");
		addEntry("Hydrostatix Master Suite", "application/vnd.hydrostatix.sof-data", "sfd-hdstx", "IANA: Hydrostatix Master Suite");
		addEntry("Hyperstudio", "application/hyperstudio", "stk", "IANA - Hyperstudio");
		addEntry("Hypertext Application Language", "application/vnd.hal+xml", "hal", "IANA: HAL");
		addEntry("HyperText Markup Language (HTML)", "text/html", "html", "Wikipedia: HTML");
		addEntry("IBM DB2 Rights Manager", "application/vnd.ibm.rights-management", "irm", "IANA: IBM DB2 Rights Manager");
		addEntry("IBM Electronic Media Management System - Secure Container", "application/vnd.ibm.secure-container", "sc", "IANA: EMMS");
		addEntry("iCalendar", "text/calendar", "ics", "Wikipedia: iCalendar");
		addEntry("ICC profile", "application/vnd.iccprofile", "icc", "IANA: ICC profile");
		addEntry("Icon Image", "image/x-icon", "ico", "Wikipedia: ICO File Format");
		addEntry("igLoader", "application/vnd.igloader", "igl", "IANA: igLoader");
		addEntry("Image Exchange Format", "image/ief", "ief", "RFC 1314");
		addEntry("ImmerVision PURE Players", "application/vnd.immervision-ivp", "ivp", "IANA: ImmerVision PURE Players");
		addEntry("ImmerVision PURE Players", "application/vnd.immervision-ivu", "ivu", "IANA: ImmerVision PURE Players");
		addEntry("IMS Networks", "application/reginfo+xml", "rif", "");
		addEntry("In3D - 3DML", "text/vnd.in3d.3dml", "3dml", "IANA: In3D");
		addEntry("In3D - 3DML", "text/vnd.in3d.spot", "spot", "IANA: In3D");
		addEntry("Initial Graphics Exchange Specification (IGES)", "model/iges", "igs", "Wikipedia: IGES");
		addEntry("Interactive Geometry Software", "application/vnd.intergeo", "i2g", "IANA: Interactive Geometry Software");
		addEntry("Interactive Geometry Software Cinderella", "application/vnd.cinderella", "cdy", "IANA: Cinderella");
		addEntry("Intercon FormNet", "application/vnd.intercon.formnet", "xpw", "IANA: Intercon FormNet");
		addEntry("International Society for Advancement of Cytometry", "application/vnd.isac.fcs", "fcs", "IANA: International Society for Advancement of Cytometry");
		addEntry("Internet Protocol Flow Information Export", "application/ipfix", "ipfix", "RFC 3917");
		addEntry("Internet Public Key Infrastructure - Certificate", "application/pkix-cert", "cer", "RFC 2585");
		addEntry("Internet Public Key Infrastructure - Certificate Management Protocole", "application/pkixcmp", "pki", "RFC 2585");
		addEntry("Internet Public Key Infrastructure - Certificate Revocation Lists", "application/pkix-crl", "crl", "RFC 2585");
		addEntry("Internet Public Key Infrastructure - Certification Path", "application/pkix-pkipath", "pkipath", "RFC 2585");
		addEntry("IOCOM Visimeet", "application/vnd.insors.igm", "igm", "IANA: IOCOM Visimeet");
		addEntry("IP Unplugged Roaming Client", "application/vnd.ipunplugged.rcprofile", "rcprofile", "IANA: IP Unplugged Roaming Client");
		addEntry("iRepository / Lucidoc Editor", "application/vnd.irepository.package+xml", "irp", "IANA: iRepository / Lucidoc Editor");
		addEntry("J2ME App Descriptor", "text/vnd.sun.j2me.app-descriptor", "jad", "IANA: J2ME App Descriptor");
		addEntry("Java Archive", "application/java-archive", "jar", "Wikipedia: JAR file format");
		addEntry("Java Bytecode File", "application/java-vm", "class", "Wikipedia: Java Bytecode");
		addEntry("Java Network Launching Protocol", "application/x-java-jnlp-file", "jnlp", "Wikipedia: Java Web Start");
		addEntry("Java Serialized Object", "application/java-serialized-object", "ser", "Java Serialization API");
		addEntry("Java Source File", "text/x-java-source,java", "java", "Wikipedia: Java");
		addEntry("JavaScript", "application/javascript", "js", "JavaScript");
		addEntry("JavaScript Module", "text/javascript", "mjs", "Wikipedia: Javascript");
		addEntry("JavaScript Module", "text/javascript", "mjs", "ECMAScript modules");
		addEntry("JavaScript Object Notation (JSON)", "application/json", "json", "Wikipedia: JSON");
		addEntry("Joda Archive", "application/vnd.joost.joda-archive", "joda", "IANA: Joda Archive");
		addEntry("JPEG 2000 Compound Image File Format", "video/jpm", "jpm", "IANA: JPM");
		addEntry("JPEG Image", "image/jpeg", "jpg, jpeg", "RFC 1314");
		addEntry("JPEG Image (Citrix client)", "image/x-citrix-jpeg", "jpg, jpeg", "RFC 1314");
		addEntry("JPEG Image (Progressive)", "image/pjpeg", "pjpeg", "JPEG image compression FAQ");
		addEntry("JPGVideo", "video/jpeg", "jpgv", "RFC 3555");
		addEntry("JSON - Linked Data", "application/ld+json", "jsonld", "Wikipedia: JSON-LD");
		addEntry("Kahootz", "application/vnd.kahootz", "ktz", "IANA: Kahootz");
		addEntry("Karaoke on Chipnuts Chipsets", "application/vnd.chipnuts.karaoke-mmd", "mmd", "IANA: Chipnuts Karaoke");
		addEntry("KDE KOffice Office Suite - Karbon", "application/vnd.kde.karbon", "karbon", "IANA: KDE KOffice Office Suite");
		addEntry("KDE KOffice Office Suite - KChart", "application/vnd.kde.kchart", "chrt", "IANA: KDE KOffice Office Suite");
		addEntry("KDE KOffice Office Suite - Kformula", "application/vnd.kde.kformula", "kfo", "IANA: KDE KOffice Office Suite");
		addEntry("KDE KOffice Office Suite - Kivio", "application/vnd.kde.kivio", "flw", "IANA: KDE KOffice Office Suite");
		addEntry("KDE KOffice Office Suite - Kontour", "application/vnd.kde.kontour", "kon", "IANA: KDE KOffice Office Suite");
		addEntry("KDE KOffice Office Suite - Kpresenter", "application/vnd.kde.kpresenter", "kpr", "IANA: KDE KOffice Office Suite");
		addEntry("KDE KOffice Office Suite - Kspread", "application/vnd.kde.kspread", "ksp", "IANA: KDE KOffice Office Suite");
		addEntry("KDE KOffice Office Suite - Kword", "application/vnd.kde.kword", "kwd", "IANA: KDE KOffice Office Suite");
		addEntry("Kenamea App", "application/vnd.kenameaapp", "htke", "IANA: Kenamea App");
		addEntry("Kidspiration", "application/vnd.kidspiration", "kia", "IANA: Kidspiration");
		addEntry("Kinar Applications", "application/vnd.kinar", "kne", "IANA: Kina Applications");
		addEntry("Kodak Storyshare", "application/vnd.kodak-descriptor", "sse", "IANA: Kodak Storyshare");
		addEntry("Laser App Enterprise", "application/vnd.las.las+xml", "lasxml", "IANA: Laser App Enterprise");
		addEntry("LaTeX", "application/x-latex", "latex", "Wikipedia: LaTeX");
		addEntry("Life Balance - Desktop Edition", "application/vnd.llamagraphics.life-balance.desktop", "lbd", "IANA: Life Balance");
		addEntry("Life Balance - Exchange Format", "application/vnd.llamagraphics.life-balance.exchange+xml", "lbe", "IANA: Life Balance");
		addEntry("Lightspeed Audio Lab", "application/vnd.jam", "jam", "IANA: Lightspeed Audio Lab");
		addEntry("Lotus 1-2-3", "application/vnd.lotus-1-2-3", "123", "IANA: Lotus 1-2-3");
		addEntry("Lotus Approach", "application/vnd.lotus-approach", "apr", "IANA: Lotus Approach");
		addEntry("Lotus Freelance", "application/vnd.lotus-freelance", "pre", "IANA: Lotus Freelance");
		addEntry("Lotus Notes", "application/vnd.lotus-notes", "nsf", "IANA: Lotus Notes");
		addEntry("Lotus Organizer", "application/vnd.lotus-organizer", "org", "IANA: Lotus Organizer");
		addEntry("Lotus Screencam", "application/vnd.lotus-screencam", "scm", "IANA: Lotus Screencam");
		addEntry("Lotus Wordpro", "application/vnd.lotus-wordpro", "lwp", "IANA: Lotus Wordpro");
		addEntry("Lucent Voice", "audio/vnd.lucent.voice", "lvp", "IANA: Lucent Voice");
		addEntry("M3U (Multimedia Playlist)", "audio/x-mpegurl", "m3u", "Wikipedia: M3U");
		addEntry("M4v", "video/x-m4v", "m4v", "Wikipedia: M4v");
		addEntry("Macintosh BinHex 4.0", "application/mac-binhex40", "hqx", "MacMIME");
		addEntry("MacPorts Port System", "application/vnd.macports.portpkg", "portpkg", "IANA: MacPorts Port System");
		addEntry("MapGuide DBXML", "application/vnd.osgeo.mapguide.package", "mgp", "IANA: MapGuide DBXML");
		addEntry("MARC Formats", "application/marc", "mrc", "RFC 2220");
		addEntry("MARC21 XML Schema", "application/marcxml+xml", "mrcx", "RFC 6207");
		addEntry("Material Exchange Format", "application/mxf", "mxf", "RFC 4539");
		addEntry("Mathematica Notebook Player", "application/vnd.wolfram.player", "nbp", "IANA: Mathematica Notebook Player");
		addEntry("Mathematica Notebooks", "application/mathematica", "ma", "IANA - Mathematica");
		addEntry("Mathematical Markup Language", "application/mathml+xml", "mathml", "W3C Math Home");
		addEntry("Mbox database files", "application/mbox", "mbox", "RFC 4155");
		addEntry("MedCalc", "application/vnd.medcalcdata", "mc1", "IANA: MedCalc");
		addEntry("Media Server Control Markup Language", "application/mediaservercontrol+xml", "mscml", "RFC 5022");
		addEntry("MediaRemote", "application/vnd.mediastation.cdkey", "cdkey", "IANA: MediaRemote");
		addEntry("Medical Waveform Encoding Format", "application/vnd.mfer", "mwf", "IANA: Medical Waveform Encoding Format");
		addEntry("Melody Format for Mobile Platform", "application/vnd.mfmp", "mfm", "IANA: Melody Format for Mobile Platform");
		addEntry("Mesh Data Type", "model/mesh", "msh", "RFC 2077");
		addEntry("Metadata Authority Description Schema", "application/mads+xml", "mads", "RFC 6207");
		addEntry("Metadata Encoding and Transmission Standard", "application/mets+xml", "mets", "RFC 6207");
		addEntry("Metadata Object Description Schema", "application/mods+xml", "mods", "RFC 6207");
		addEntry("Metalink", "application/metalink4+xml", "meta4", "Wikipedia: Metalink");
		addEntry("Micro CADAM Helix D&D", "application/vnd.mcd", "mcd", "IANA: Micro CADAM Helix D&D");
		addEntry("Micrografx", "application/vnd.micrografx.flo", "flo", "IANA: Micrografx");
		addEntry("Micrografx iGrafx Professional", "application/vnd.micrografx.igx", "igx", "IANA: Micrografx");
		addEntry("MICROSEC e-Szign�", "application/vnd.eszigno3+xml", "es3", "IANA: MICROSEC e-Szign�");
		addEntry("Microsoft Access", "application/x-msaccess", "mdb", "Wikipedia: Microsoft Access");
		addEntry("Microsoft Advanced Systems Format (ASF)", "video/x-ms-asf", "asf", "Wikipedia: Advanced Systems Format (ASF)");
		addEntry("Microsoft Application", "application/x-msdownload", "exe", "Wikipedia: EXE");
		addEntry("Microsoft Artgalry", "application/vnd.ms-artgalry", "cil", "IANA: MS Artgalry");
		addEntry("Microsoft Cabinet File", "application/vnd.ms-cab-compressed", "cab", "IANA: MS Cabinet File");
		addEntry("Microsoft Class Server", "application/vnd.ms-ims", "ims", "IANA: MS Class Server");
		addEntry("Microsoft ClickOnce", "application/x-ms-application", "application", "Wikipedia: ClickOnce");
		addEntry("Microsoft Clipboard Clip", "application/x-msclip", "clp", "Wikipedia: Clipboard");
		addEntry("Microsoft Document Imaging Format", "image/vnd.ms-modi", "mdi", "Wikipedia: Microsoft Document Image Format");
		addEntry("Microsoft Embedded OpenType", "application/vnd.ms-fontobject", "eot", "IANA: MS Embedded OpenType");
		addEntry("Microsoft Excel", "application/vnd.ms-excel", "xls", "IANA: MS Excel");
		addEntry("Microsoft Excel - Add-In File", "application/vnd.ms-excel.addin.macroenabled.12", "xlam", "IANA: MS Excel");
		addEntry("Microsoft Excel - Binary Workbook", "application/vnd.ms-excel.sheet.binary.macroenabled.12", "xlsb", "IANA: MS Excel");
		addEntry("Microsoft Excel - Macro-Enabled Template File", "application/vnd.ms-excel.template.macroenabled.12", "xltm", "IANA: MS Excel");
		addEntry("Microsoft Excel - Macro-Enabled Workbook", "application/vnd.ms-excel.sheet.macroenabled.12", "xlsm", "IANA: MS Excel");
		addEntry("Microsoft Html Help File", "application/vnd.ms-htmlhelp", "chm", "IANA:MS Html Help File");
		addEntry("Microsoft Information Card", "application/x-mscardfile", "crd", "Wikipedia: Information Card");
		addEntry("Microsoft Learning Resource Module", "application/vnd.ms-lrm", "lrm", "IANA: MS Learning Resource Module");
		addEntry("Microsoft MediaView", "application/x-msmediaview", "mvb", "Windows Help");
		addEntry("Microsoft Money", "application/x-msmoney", "mny", "Wikipedia: Microsoft Money");
		addEntry("Microsoft Office - OOXML - Presentation", "application/vnd.openxmlformats-officedocument.presentationml.presentation", "pptx", "IANA: OOXML - Presentation");
		addEntry("Microsoft Office - OOXML - Presentation (Slide)", "application/vnd.openxmlformats-officedocument.presentationml.slide", "sldx", "IANA: OOXML - Presentation");
		addEntry("Microsoft Office - OOXML - Presentation (Slideshow)", "application/vnd.openxmlformats-officedocument.presentationml.slideshow", "ppsx", "IANA: OOXML - Presentation");
		addEntry("Microsoft Office - OOXML - Presentation Template", "application/vnd.openxmlformats-officedocument.presentationml.template", "potx", "IANA: OOXML - Presentation Template");
		addEntry("Microsoft Office - OOXML - Spreadsheet", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "xlsx", "IANA: OOXML - Spreadsheet");
		addEntry("Microsoft Office - OOXML - Spreadsheet Template", "application/vnd.openxmlformats-officedocument.spreadsheetml.template", "xltx", "IANA: OOXML - Spreadsheet Template");
		addEntry("Microsoft Office - OOXML - Word Document", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "docx", "IANA: OOXML - Word Document");
		addEntry("Microsoft Office - OOXML - Word Document Template", "application/vnd.openxmlformats-officedocument.wordprocessingml.template", "dotx", "IANA: OOXML - Word Document Template");
		addEntry("Microsoft Office Binder", "application/x-msbinder", "obd", "Wikipedia: Microsoft Shared Tools");
		addEntry("Microsoft Office System Release Theme", "application/vnd.ms-officetheme", "thmx", "IANA: MS Office System Release Theme");
		addEntry("Microsoft OneNote", "application/onenote", "onetoc", "MS OneNote 2010");
		addEntry("Microsoft PlayReady Ecosystem", "audio/vnd.ms-playready.media.pya", "pya", "IANA: Microsoft PlayReady Ecosystem");
		addEntry("Microsoft PlayReady Ecosystem Video", "video/vnd.ms-playready.media.pyv", "pyv", "IANA: Microsoft PlayReady Ecosystem");
		addEntry("Microsoft PowerPoint", "application/vnd.ms-powerpoint", "ppt", "IANA: MS PowerPoint");
		addEntry("Microsoft PowerPoint - Add-in file", "application/vnd.ms-powerpoint.addin.macroenabled.12", "ppam", "IANA: MS PowerPoint");
		addEntry("Microsoft PowerPoint - Macro-Enabled Open XML Slide", "application/vnd.ms-powerpoint.slide.macroenabled.12", "sldm", "IANA: MS PowerPoint");
		addEntry("Microsoft PowerPoint - Macro-Enabled Presentation File", "application/vnd.ms-powerpoint.presentation.macroenabled.12", "pptm", "IANA: MS PowerPoint");
		addEntry("Microsoft PowerPoint - Macro-Enabled Slide Show File", "application/vnd.ms-powerpoint.slideshow.macroenabled.12", "ppsm", "IANA: MS PowerPoint");
		addEntry("Microsoft PowerPoint - Macro-Enabled Template File", "application/vnd.ms-powerpoint.template.macroenabled.12", "potm", "IANA: MS PowerPoint");
		addEntry("Microsoft Project", "application/vnd.ms-project", "mpp", "IANA: MS PowerPoint");
		addEntry("Microsoft Publisher", "application/x-mspublisher", "pub", "Wikipedia: Microsoft Publisher");
		addEntry("Microsoft Schedule+", "application/x-msschedule", "scd", "Wikipedia: Microsoft Schedule Plus");
		addEntry("Microsoft Silverlight", "application/x-silverlight-app", "xap", "Wikipedia: Silverlight");
		addEntry("Microsoft Trust UI Provider - Certificate Trust Link", "application/vnd.ms-pki.stl", "stl", "IANA: MS Trust UI Provider");
		addEntry("Microsoft Trust UI Provider - Security Catalog", "application/vnd.ms-pki.seccat", "cat", "IANA: MS Trust UI Provider");
		addEntry("Microsoft Visio", "application/vnd.visio", "vsd", "IANA: Visio");
		addEntry("Microsoft Visio 2013", "application/vnd.visio2013", "vsdx", "IANA: Visio");
		addEntry("Microsoft Windows Media", "video/x-ms-wm", "wm", "Wikipedia: Advanced Systems Format (ASF)");
		addEntry("Microsoft Windows Media Audio", "audio/x-ms-wma", "wma", "Wikipedia: Windows Media Audio");
		addEntry("Microsoft Windows Media Audio Redirector", "audio/x-ms-wax", "wax", "Windows Media Metafiles");
		addEntry("Microsoft Windows Media Audio/Video Playlist", "video/x-ms-wmx", "wmx", "Wikipedia: Advanced Systems Format (ASF)");
		addEntry("Microsoft Windows Media Player Download Package", "application/x-ms-wmd", "wmd", "Wikipedia: Windows Media Player");
		addEntry("Microsoft Windows Media Player Playlist", "application/vnd.ms-wpl", "wpl", "IANA: MS Windows Media Player Playlist");
		addEntry("Microsoft Windows Media Player Skin Package", "application/x-ms-wmz", "wmz", "Wikipedia: Windows Media Player");
		addEntry("Microsoft Windows Media Video", "video/x-ms-wmv", "wmv", "Wikipedia: Advanced Systems Format (ASF)");
		addEntry("Microsoft Windows Media Video Playlist", "video/x-ms-wvx", "wvx", "Wikipedia: Advanced Systems Format (ASF)");
		addEntry("Microsoft Windows Metafile", "application/x-msmetafile", "wmf", "Wikipedia: Windows Metafile");
		addEntry("Microsoft Windows Terminal Services", "application/x-msterminal", "trm", "Wikipedia: Terminal Server");
		addEntry("Microsoft Word", "application/msword", "doc", "Wikipedia: Microsoft Word");
		addEntry("Microsoft Word - Macro-Enabled Document", "application/vnd.ms-word.document.macroenabled.12", "docm", "IANA: MS Word");
		addEntry("Microsoft Word - Macro-Enabled Template", "application/vnd.ms-word.template.macroenabled.12", "dotm", "IANA: MS Word");
		addEntry("Microsoft Wordpad", "application/x-mswrite", "wri", "Wikipedia: Wordpad");
		addEntry("Microsoft Works", "application/vnd.ms-works", "wps", "IANA: MS Works");
		addEntry("Microsoft XAML Browser Application", "application/x-ms-xbap", "xbap", "Wikipedia: XAML Browser");
		addEntry("Microsoft XML Paper Specification", "application/vnd.ms-xpsdocument", "xps", "IANA: MS XML Paper Specification");
		addEntry("MIDI", "audio/midi", "midi", "Wikipedia: MIDI");
		addEntry("MIDI - Musical Instrument Digital Interface", "audio/midi", "mid", "Wikipedia: MIDI");
		addEntry("MiniPay", "application/vnd.ibm.minipay", "mpy", "IANA: MiniPay");
		addEntry("MO:DCA-P", "application/vnd.ibm.modcap", "afp", "IANA: MO:DCA-P");
		addEntry("Mobile Information Device Profile", "application/vnd.jcp.javame.midlet-rms", "rms", "IANA: Mobile Information Device Profile");
		addEntry("MobileTV", "application/vnd.tmobile-livetv", "tmo", "IANA: MobileTV");
		addEntry("Mobipocket", "application/x-mobipocket-ebook", "prc", "Wikipedia: Mobipocket");
		addEntry("Mobius Management Systems - Basket file", "application/vnd.mobius.mbk", "mbk", "IANA: Mobius Management Systems");
		addEntry("Mobius Management Systems - Distribution Database", "application/vnd.mobius.dis", "dis", "IANA: Mobius Management Systems");
		addEntry("Mobius Management Systems - Policy Definition Language File", "application/vnd.mobius.plc", "plc", "IANA: Mobius Management Systems");
		addEntry("Mobius Management Systems - Query File", "application/vnd.mobius.mqy", "mqy", "IANA: Mobius Management Systems");
		addEntry("Mobius Management Systems - Script Language", "application/vnd.mobius.msl", "msl", "IANA: Mobius Management Systems");
		addEntry("Mobius Management Systems - Topic Index File", "application/vnd.mobius.txf", "txf", "IANA: Mobius Management Systems");
		addEntry("Mobius Management Systems - UniversalArchive", "application/vnd.mobius.daf", "daf", "IANA: Mobius Management Systems");
		addEntry("mod_fly / fly.cgi", "text/vnd.fly", "fly", "IANA: Fly");
		addEntry("Mophun Certificate", "application/vnd.mophun.certificate", "mpc", "IANA: Mophun Certificate");
		addEntry("Mophun VM", "application/vnd.mophun.application", "mpn", "IANA: Mophun VM");
		addEntry("Motion JPEG 2000", "video/mj2", "mj2", "IANA: MJ2");
		addEntry("MPEG Audio", "audio/mpeg", "mp3, mpga", "Wikipedia: MPGA");
		addEntry("MPEG Transport Stream", "video/mp2t", "ts", "Wikipedia: MPEG Transport Stream");
		addEntry("MPEG Url", "video/vnd.mpegurl", "mxu", "IANA: MPEG Url");
		addEntry("MPEG Video", "video/mpeg", "mpeg", "Wikipedia: MPEG");
		addEntry("MPEG-21", "application/mp21", "m21", "Wikipedia: MPEG-21");
		addEntry("MPEG-4 Audio", "audio/mp4", "mp4a", "Wikipedia: MP4A");
		addEntry("MPEG-4 Video", "video/mp4", "mp4", "Wikipedia: MP4");
		addEntry("MPEG4", "application/mp4", "mp4", "RFC 4337");
		addEntry("Multimedia Playlist Unicode", "application/vnd.apple.mpegurl", "m3u8", "Wikipedia: M3U");
		addEntry("MUsical Score Interpreted Code Invented for the ASCII designation of Notation", "application/vnd.musician", "mus", "IANA: MUSICIAN");
		addEntry("Muvee Automatic Video Editing", "application/vnd.muvee.style", "msty", "IANA: Muvee");
		addEntry("MXML", "application/xv+xml", "mxml", "Wikipedia: MXML");
		addEntry("N-Gage Game Data", "application/vnd.nokia.n-gage.data", "ngdat", "IANA: N-Gage Game Data");
		addEntry("N-Gage Game Installer", "application/vnd.nokia.n-gage.symbian.install", "n-gage", "IANA: N-Gage Game Installer");
		addEntry("Navigation Control file for XML (for ePub)", "application/x-dtbncx+xml", "ncx", "Wikipedia: EPUB");
		addEntry("Network Common Data Form (NetCDF)", "application/x-netcdf", "nc", "Wikipedia: NetCDF");
		addEntry("neuroLanguage", "application/vnd.neurolanguage.nlu", "nlu", "IANA: neuroLanguage");
		addEntry("New Moon Liftoff/DNA", "application/vnd.dna", "dna", "IANA: New Moon Liftoff/DNA");
		addEntry("NobleNet Directory", "application/vnd.noblenet-directory", "nnd", "IANA: NobleNet Directory");
		addEntry("NobleNet Sealer", "application/vnd.noblenet-sealer", "nns", "IANA: NobleNet Sealer");
		addEntry("NobleNet Web", "application/vnd.noblenet-web", "nnw", "IANA: NobleNet Web");
		addEntry("Nokia Radio Application - Preset", "application/vnd.nokia.radio-preset", "rpst", "IANA: Nokia Radio Application");
		addEntry("Nokia Radio Application - Preset", "application/vnd.nokia.radio-presets", "rpss", "IANA: Nokia Radio Application");
		addEntry("Notation3", "text/n3", "n3", "Wikipedia: Notation3");
		addEntry("Novadigm's RADIA and EDM products", "application/vnd.novadigm.edm", "edm", "IANA: Novadigm's RADIA and EDM products");
		addEntry("Novadigm's RADIA and EDM products", "application/vnd.novadigm.edx", "edx", "IANA: Novadigm's RADIA and EDM products");
		addEntry("Novadigm's RADIA and EDM products", "application/vnd.novadigm.ext", "ext", "IANA: Novadigm's RADIA and EDM products");
		addEntry("NpGraphIt", "application/vnd.flographit", "gph", "IANA: FloGraphIt");
		addEntry("Nuera ECELP 4800", "audio/vnd.nuera.ecelp4800", "ecelp4800", "IANA: ECELP 4800");
		addEntry("Nuera ECELP 7470", "audio/vnd.nuera.ecelp7470", "ecelp7470", "IANA: ECELP 7470");
		addEntry("Nuera ECELP 9600", "audio/vnd.nuera.ecelp9600", "ecelp9600", "IANA: ECELP 9600");
		addEntry("Office Document Architecture", "application/oda", "oda", "RFC 2161");
		addEntry("Ogg", "application/ogg", "ogx", "Wikipedia: Ogg");
		addEntry("Ogg Audio", "audio/ogg", "oga", "Wikipedia: Ogg");
		addEntry("Ogg Video", "video/ogg", "ogv", "Wikipedia: Ogg");
		addEntry("OMA Download Agents", "application/vnd.oma.dd2+xml", "dd2", "IANA: OMA Download Agents");
		addEntry("Open Document Text Web", "application/vnd.oasis.opendocument.text-web", "oth", "IANA: OpenDocument Text Web");
		addEntry("Open eBook Publication Structure", "application/oebps-package+xml", "opf", "Wikipedia: Open eBook");
		addEntry("Open Financial Exchange", "application/vnd.intu.qbo", "qbo", "IANA: Open Financial Exchange");
		addEntry("Open Office Extension", "application/vnd.openofficeorg.extension", "oxt", "IANA: Open Office Extension");
		addEntry("Open Score Format", "application/vnd.yamaha.openscoreformat", "osf", "IANA: Open Score Format");
		addEntry("Open Web Media Project - Audio", "audio/webm", "weba", "WebM Project");
		addEntry("Open Web Media Project - Video", "video/webm", "webm", "WebM Project");
		addEntry("OpenDocument Chart", "application/vnd.oasis.opendocument.chart", "odc", "IANA: OpenDocument Chart");
		addEntry("OpenDocument Chart Template", "application/vnd.oasis.opendocument.chart-template", "otc", "IANA: OpenDocument Chart Template");
		addEntry("OpenDocument Database", "application/vnd.oasis.opendocument.database", "odb", "IANA: OpenDocument Database");
		addEntry("OpenDocument Formula", "application/vnd.oasis.opendocument.formula", "odf", "IANA: OpenDocument Formula");
		addEntry("OpenDocument Formula Template", "application/vnd.oasis.opendocument.formula-template", "odft", "IANA: OpenDocument Formula Template");
		addEntry("OpenDocument Graphics", "application/vnd.oasis.opendocument.graphics", "odg", "IANA: OpenDocument Graphics");
		addEntry("OpenDocument Graphics Template", "application/vnd.oasis.opendocument.graphics-template", "otg", "IANA: OpenDocument Graphics Template");
		addEntry("OpenDocument Image", "application/vnd.oasis.opendocument.image", "odi", "IANA: OpenDocument Image");
		addEntry("OpenDocument Image Template", "application/vnd.oasis.opendocument.image-template", "oti", "IANA: OpenDocument Image Template");
		addEntry("OpenDocument Presentation", "application/vnd.oasis.opendocument.presentation", "odp", "IANA: OpenDocument Presentation");
		addEntry("OpenDocument Presentation Template", "application/vnd.oasis.opendocument.presentation-template", "otp", "IANA: OpenDocument Presentation Template");
		addEntry("OpenDocument Spreadsheet", "application/vnd.oasis.opendocument.spreadsheet", "ods", "IANA: OpenDocument Spreadsheet");
		addEntry("OpenDocument Spreadsheet Template", "application/vnd.oasis.opendocument.spreadsheet-template", "ots", "IANA: OpenDocument Spreadsheet Template");
		addEntry("OpenDocument Text", "application/vnd.oasis.opendocument.text", "odt", "IANA: OpenDocument Text");
		addEntry("OpenDocument Text Master", "application/vnd.oasis.opendocument.text-master", "odm", "IANA: OpenDocument Text Master");
		addEntry("OpenDocument Text Template", "application/vnd.oasis.opendocument.text-template", "ott", "IANA: OpenDocument Text Template");
		addEntry("OpenGL Textures (KTX)", "image/ktx", "ktx", "KTX File Format");
		addEntry("OpenOffice - Calc (Spreadsheet)", "application/vnd.sun.xml.calc", "sxc", "Wikipedia: OpenOffice");
		addEntry("OpenOffice - Calc Template (Spreadsheet)", "application/vnd.sun.xml.calc.template", "stc", "Wikipedia: OpenOffice");
		addEntry("OpenOffice - Draw (Graphics)", "application/vnd.sun.xml.draw", "sxd", "Wikipedia: OpenOffice");
		addEntry("OpenOffice - Draw Template (Graphics)", "application/vnd.sun.xml.draw.template", "std", "Wikipedia: OpenOffice");
		addEntry("OpenOffice - Impress (Presentation)", "application/vnd.sun.xml.impress", "sxi", "Wikipedia: OpenOffice");
		addEntry("OpenOffice - Impress Template (Presentation)", "application/vnd.sun.xml.impress.template", "sti", "Wikipedia: OpenOffice");
		addEntry("OpenOffice - Math (Formula)", "application/vnd.sun.xml.math", "sxm", "Wikipedia: OpenOffice");
		addEntry("OpenOffice - Writer (Text - HTML)", "application/vnd.sun.xml.writer", "sxw", "Wikipedia: OpenOffice");
		addEntry("OpenOffice - Writer (Text - HTML)", "application/vnd.sun.xml.writer.global", "sxg", "Wikipedia: OpenOffice");
		addEntry("OpenOffice - Writer Template (Text - HTML)", "application/vnd.sun.xml.writer.template", "stw", "Wikipedia: OpenOffice");
		addEntry("OpenType Font File", "application/x-font-otf", "otf", "OpenType Font File");
		addEntry("Opus Audio", "audio/opus", "opus", "Wikipedia: Opus Audio");
		addEntry("OSFPVG", "application/vnd.yamaha.openscoreformat.osfpvg+xml", "osfpvg", "IANA: OSFPVG");
		addEntry("OSGi Deployment Package", "application/vnd.osgi.dp", "dp", "IANA: OSGi Deployment Package");
		addEntry("PalmOS Data", "application/vnd.palm", "pdb", "IANA: PalmOS Data");
		addEntry("Pascal Source File", "text/x-pascal", "p", "Wikipedia: Pascal");
		addEntry("PawaaFILE", "application/vnd.pawaafile", "paw", "IANA: PawaaFILE");
		addEntry("PCL 6 Enhanced (Formely PCL XL)", "application/vnd.hp-pclxl", "pclxl", "IANA: HP PCL XL");
		addEntry("Pcsel eFIF File", "application/vnd.picsel", "efif", "IANA: Picsel eFIF File");
		addEntry("PCX Image", "image/x-pcx", "pcx", "Wikipedia: PCX");
		addEntry("Photoshop Document", "image/vnd.adobe.photoshop", "psd", "Wikipedia: Photoshop Document");
		addEntry("PICSRules", "application/pics-rules", "prf", "W3C PICSRules");
		addEntry("PICT Image", "image/x-pict", "pic", "Wikipedia: PICT");
		addEntry("pIRCh", "application/x-chat", "chat", "Wikipedia: pIRCh");
		addEntry("PKCS #10 - Certification Request Standard", "application/pkcs10", "p10", "RFC 2986");
		addEntry("PKCS #12 - Personal Information Exchange Syntax Standard", "application/x-pkcs12", "p12", "RFC 2986");
		addEntry("PKCS #7 - Cryptographic Message Syntax Standard", "application/pkcs7-mime", "p7m", "RFC 2315");
		addEntry("PKCS #7 - Cryptographic Message Syntax Standard", "application/pkcs7-signature", "p7s", "RFC 2315");
		addEntry("PKCS #7 - Cryptographic Message Syntax Standard (Certificate Request Response)", "application/x-pkcs7-certreqresp", "p7r", "RFC 2986");
		addEntry("PKCS #7 - Cryptographic Message Syntax Standard (Certificates)", "application/x-pkcs7-certificates", "p7b", "RFC 2986");
		addEntry("PKCS #8 - Private-Key Information Syntax Standard", "application/pkcs8", "p8", "RFC 5208");
		addEntry("PocketLearn Viewers", "application/vnd.pocketlearn", "plf", "IANA: PocketLearn Viewers");
		addEntry("Portable Anymap Image", "image/x-portable-anymap", "pnm", "Wikipedia: Netpbm Format");
		addEntry("Portable Bitmap Format", "image/x-portable-bitmap", "pbm", "Wikipedia: Netpbm Format");
		addEntry("Portable Compiled Format", "application/x-font-pcf", "pcf", "Wikipedia: Portable Compiled Format");
		addEntry("Portable Font Resource", "application/font-tdpfr", "pfr", "RFC 3073");
		addEntry("Portable Game Notation (Chess Games)", "application/x-chess-pgn", "pgn", "Wikipedia: Portable Game Notationb");
		addEntry("Portable Graymap Format", "image/x-portable-graymap", "pgm", "Wikipedia: Netpbm Format");
		addEntry("Portable Network Graphics (PNG)", "image/png", "png", "RFC 2083");
		addEntry("Portable Network Graphics (PNG) (Citrix client)", "image/x-citrix-png", "png", "RFC 2083");
		addEntry("Portable Network Graphics (PNG) (x-token)", "image/x-png", "png", "RFC 2083");
		addEntry("Portable Pixmap Format", "image/x-portable-pixmap", "ppm", "Wikipedia: Netpbm Format");
		addEntry("Portable Symmetric Key Container", "application/pskc+xml", "pskcxml", "RFC 6030");
		addEntry("PosML", "application/vnd.ctc-posml", "pml", "IANA: PosML");
		addEntry("PostScript", "application/postscript", "ai", "Wikipedia: PostScript");
		addEntry("PostScript Fonts", "application/x-font-type1", "pfa", "Wikipedia: PostScript Fonts");
		addEntry("PowerBuilder", "application/vnd.powerbuilder6", "pbd", "IANA: PowerBuilder");
		addEntry("Pretty Good Privacy", "application/pgp-encrypted", "pgp", "RFC 2015");
		addEntry("Pretty Good Privacy - Signature", "application/pgp-signature", "pgp", "RFC 2015");
		addEntry("Preview Systems ZipLock/VBox", "application/vnd.previewsystems.box", "box", "IANA: Preview Systems ZipLock/Vbox");
		addEntry("Princeton Video Image", "application/vnd.pvi.ptid1", "ptid", "IANA: Princeton Video Image");
		addEntry("Pronunciation Lexicon Specification", "application/pls+xml", "pls", "RFC 4267");
		addEntry("Proprietary P&G Standard Reporting System", "application/vnd.pg.format", "str", "IANA: Proprietary P&G Standard Reporting System");
		addEntry("Proprietary P&G Standard Reporting System", "application/vnd.pg.osasli", "ei6", "IANA: Proprietary P&G Standard Reporting System");
		addEntry("PRS Lines Tag", "text/prs.lines.tag", "dsc", "IANA: PRS Lines Tag");
		addEntry("PSF Fonts", "application/x-font-linux-psf", "psf", "PSF Fonts");
		addEntry("PubliShare Objects", "application/vnd.publishare-delta-tree", "qps", "IANA: PubliShare Objects");
		addEntry("Qualcomm's Plaza Mobile Internet", "application/vnd.pmi.widget", "wg", "IANA: Qualcomm's Plaza Mobile Internet");
		addEntry("QuarkXpress", "application/vnd.quark.quarkxpress", "qxd", "IANA: QuarkXPress");
		addEntry("QUASS Stream Player", "application/vnd.epson.esf", "esf", "IANA: QUASS Stream Player");
		addEntry("QUASS Stream Player", "application/vnd.epson.msf", "msf", "IANA: QUASS Stream Player");
		addEntry("QUASS Stream Player", "application/vnd.epson.ssf", "ssf", "IANA: QUASS Stream Player");
		addEntry("QuickAnime Player", "application/vnd.epson.quickanime", "qam", "IANA: QuickAnime Player");
		addEntry("Quicken", "application/vnd.intu.qfx", "qfx", "IANA: Quicken");
		addEntry("Quicktime Video", "video/quicktime", "qt", "Wikipedia: Quicktime");
		addEntry("RAR Archive", "application/x-rar-compressed", "rar", "Wikipedia: RAR");
		addEntry("Real Audio Sound", "audio/x-pn-realaudio", "ram", "Wikipedia: RealPlayer");
		addEntry("Real Audio Sound", "audio/x-pn-realaudio-plugin", "rmp", "Wikipedia: RealPlayer");
		addEntry("Really Simple Discovery", "application/rsd+xml", "rsd", "Wikipedia: Really Simple Discovery");
		addEntry("RealMedia", "application/vnd.rn-realmedia", "rm", "");
		addEntry("RealVNC", "application/vnd.realvnc.bed", "bed", "IANA: RealVNC");
		addEntry("Recordare Applications", "application/vnd.recordare.musicxml", "mxl", "IANA: Recordare Apps");
		addEntry("Recordare Applications", "application/vnd.recordare.musicxml+xml", "musicxml", "IANA: Recordare Apps");
		addEntry("Relax NG Compact Syntax", "application/relax-ng-compact-syntax", "rnc", "Relax NG");
		addEntry("RemoteDocs R-Viewer", "application/vnd.data-vision.rdz", "rdz", "IANA: Data-Vision");
		addEntry("Resource Description Framework", "application/rdf+xml", "rdf", "RFC 3870");
		addEntry("RetroPlatform Player", "application/vnd.cloanto.rp9", "rp9", "IANA: RetroPlatform Player");
		addEntry("RhymBox", "application/vnd.jisp", "jisp", "IANA: RhymBox");
		addEntry("Rich Text Format", "application/rtf", "rtf", "Wikipedia: Rich Text Format");
		addEntry("Rich Text Format (RTF)", "text/richtext", "rtx", "Wikipedia: Rich Text Format");
		addEntry("ROUTE 66 Location Based Services", "application/vnd.route66.link66+xml", "link66", "IANA: ROUTE 66");
		addEntry("RSS - Really Simple Syndication", "application/rss+xml", "rss, xml", "Wikipedia: RSS");
		addEntry("S Hexdump Format", "application/shf+xml", "shf", "RFC 4194");
		addEntry("SailingTracker", "application/vnd.sailingtracker.track", "st", "IANA: SailingTracker");
		addEntry("Scalable Vector Graphics (SVG)", "image/svg+xml", "svg", "Wikipedia: SVG");
		addEntry("ScheduleUs", "application/vnd.sus-calendar", "sus", "IANA: ScheduleUs");
		addEntry("Search/Retrieve via URL Response Format", "application/sru+xml", "sru", "RFC 6207");
		addEntry("Secure Electronic Transaction - Payment", "application/set-payment-initiation", "setpay", "IANA: SET Payment");
		addEntry("Secure Electronic Transaction - Registration", "application/set-registration-initiation", "setreg", "IANA: SET Registration");
		addEntry("Secured eMail", "application/vnd.sema", "sema", "IANA: Secured eMail");
		addEntry("Secured eMail", "application/vnd.semd", "semd", "IANA: Secured eMail");
		addEntry("Secured eMail", "application/vnd.semf", "semf", "IANA: Secured eMail");
		addEntry("SeeMail", "application/vnd.seemail", "see", "IANA: SeeMail");
		addEntry("Server Normal Format", "application/x-font-snf", "snf", "Wikipedia: Server Normal Format");
		addEntry("Server-Based Certificate Validation Protocol - Validation Policies - Request", "application/scvp-vp-request", "spq", "RFC 5055");
		addEntry("Server-Based Certificate Validation Protocol - Validation Policies - Response", "application/scvp-vp-response", "spp", "RFC 5055");
		addEntry("Server-Based Certificate Validation Protocol - Validation Request", "application/scvp-cv-request", "scq", "RFC 5055");
		addEntry("Server-Based Certificate Validation Protocol - Validation Response", "application/scvp-cv-response", "scs", "RFC 5055");
		addEntry("Session Description Protocol", "application/sdp", "sdp", "RFC 2327");
		addEntry("Setext", "text/x-setext", "etx", "Wikipedia: Setext");
		addEntry("SGI Movie", "video/x-sgi-movie", "movie", "SGI Facts");
		addEntry("Shana Informed Filler", "application/vnd.shana.informed.formdata", "ifm", "IANA: Shana Informed Filler");
		addEntry("Shana Informed Filler", "application/vnd.shana.informed.formtemplate", "itp", "IANA: Shana Informed Filler");
		addEntry("Shana Informed Filler", "application/vnd.shana.informed.interchange", "iif", "IANA: Shana Informed Filler");
		addEntry("Shana Informed Filler", "application/vnd.shana.informed.package", "ipk", "IANA: Shana Informed Filler");
		addEntry("Sharing Transaction Fraud Data", "application/thraud+xml", "tfi", "RFC 5941");
		addEntry("Shell Archive", "application/x-shar", "shar", "Wikipedia: Shell Archie");
		addEntry("Silicon Graphics RGB Bitmap", "image/x-rgb", "rgb", "RGB Image Format");
		addEntry("SimpleAnimeLite Player", "application/vnd.epson.salt", "slt", "IANA: SimpleAnimeLite Player");
		addEntry("Simply Accounting", "application/vnd.accpac.simply.aso", "aso", "IANA: Simply Accounting");
		addEntry("Simply Accounting - Data Import", "application/vnd.accpac.simply.imp", "imp", "IANA: Simply Accounting");
		addEntry("SimTech MindMapper", "application/vnd.simtech-mindmapper", "twd", "IANA: SimTech MindMapper");
		addEntry("Sixth Floor Media - CommonSpace", "application/vnd.commonspace", "csp", "IANA: CommonSpace");
		addEntry("SMAF Audio", "application/vnd.yamaha.smaf-audio", "saf", "IANA: SMAF Audio");
		addEntry("SMAF File", "application/vnd.smaf", "mmf", "IANA: SMAF File");
		addEntry("SMAF Phrase", "application/vnd.yamaha.smaf-phrase", "spf", "IANA: SMAF Phrase");
		addEntry("SMART Technologies Apps", "application/vnd.smart.teacher", "teacher", "IANA: SMART Technologies Apps");
		addEntry("SourceView Document", "application/vnd.svd", "svd", "IANA: SourceView Document");
		addEntry("SPARQL - Query", "application/sparql-query", "rq", "W3C SPARQL");
		addEntry("SPARQL - Results", "application/sparql-results+xml", "srx", "W3C SPARQL");
		addEntry("Speech Recognition Grammar Specification", "application/srgs", "gram", "W3C Speech Grammar");
		addEntry("Speech Recognition Grammar Specification - XML", "application/srgs+xml", "grxml", "W3C Speech Grammar");
		addEntry("Speech Synthesis Markup Language", "application/ssml+xml", "ssml", "W3C Speech Synthesis");
		addEntry("SSEYO Koan Play File", "application/vnd.koan", "skp", "IANA: SSEYO Koan Play File");
		addEntry("Standard Generalized Markup Language (SGML)", "text/sgml", "sgml", "Wikipedia: SGML");
		addEntry("StarOffice - Calc", "application/vnd.stardivision.calc", "sdc", "");
		addEntry("StarOffice - Draw", "application/vnd.stardivision.draw", "sda", "");
		addEntry("StarOffice - Impress", "application/vnd.stardivision.impress", "sdd", "");
		addEntry("StarOffice - Math", "application/vnd.stardivision.math", "smf", "");
		addEntry("StarOffice - Writer", "application/vnd.stardivision.writer", "sdw", "");
		addEntry("StarOffice - Writer (Global)", "application/vnd.stardivision.writer-global", "sgl", "");
		addEntry("StepMania", "application/vnd.stepmania.stepchart", "sm", "IANA: StepMania");
		addEntry("Stuffit Archive", "application/x-stuffit", "sit", "Wikipedia: Stuffit");
		addEntry("Stuffit Archive", "application/x-stuffitx", "sitx", "Wikipedia: Stuffit");
		addEntry("SudokuMagic", "application/vnd.solent.sdkm+xml", "sdkm", "IANA: SudokuMagic");
		addEntry("Sugar Linux Application Bundle", "application/vnd.olpc-sugar", "xo", "IANA: Sugar Linux App Bundle");
		addEntry("Sun Audio - Au file format", "audio/basic", "au", "Wikipedia: Sun audio");
		addEntry("SundaHus WQ", "application/vnd.wqd", "wqd", "IANA: SundaHus WQ");
		addEntry("Symbian Install Package", "application/vnd.symbian.install", "sis", "IANA: Symbian Install");
		addEntry("Synchronized Multimedia Integration Language", "application/smil+xml", "smi", "RFC 4536");
		addEntry("SyncML", "application/vnd.syncml+xml", "xsm", "IANA: SyncML");
		addEntry("SyncML - Device Management", "application/vnd.syncml.dm+wbxml", "bdm", "IANA: SyncML");
		addEntry("SyncML - Device Management", "application/vnd.syncml.dm+xml", "xdm", "IANA: SyncML");
		addEntry("System V Release 4 CPIO Archive", "application/x-sv4cpio", "sv4cpio", "Wikipedia: pax");
		addEntry("System V Release 4 CPIO Checksum Data", "application/x-sv4crc", "sv4crc", "Wikipedia: pax");
		addEntry("Systems Biology Markup Language", "application/sbml+xml", "sbml", "RFC 3823");
		addEntry("Tab Seperated Values", "text/tab-separated-values", "tsv", "Wikipedia: TSV");
		addEntry("Tagged Image File Format", "image/tiff", "tiff", "Wikipedia: TIFF");
		addEntry("Tao Intent", "application/vnd.tao.intent-module-archive", "tao", "IANA: Tao Intent");
		addEntry("Tar File (Tape Archive)", "application/x-tar", "tar", "Wikipedia: Tar");
		addEntry("Tcl Script", "application/x-tcl", "tcl", "Wikipedia: Tcl");
		addEntry("TeX", "application/x-tex", "tex", "Wikipedia: TeX");
		addEntry("TeX Font Metric", "application/x-tex-tfm", "tfm", "Wikipedia: TeX Font Metric");
		addEntry("Text Encoding and Interchange", "application/tei+xml", "tei", "RFC 6129");
		addEntry("Text File", "text/plain", "txt", "Wikipedia: Text File");
		addEntry("TIBCO Spotfire", "application/vnd.spotfire.dxp", "dxp", "IANA: TIBCO Spotfire");
		addEntry("TIBCO Spotfire", "application/vnd.spotfire.sfs", "sfs", "IANA: TIBCO Spotfire");
		addEntry("Time Stamped Data Envelope", "application/timestamped-data", "tsd", "RFC 5955");
		addEntry("TRI Systems Config", "application/vnd.trid.tpt", "tpt", "IANA: TRI Systems");
		addEntry("Triscape Map Explorer", "application/vnd.triscape.mxs", "mxs", "IANA: Triscape Map Explorer");
		addEntry("troff", "text/troff", "t", "Wikipedia: troff");
		addEntry("True BASIC", "application/vnd.trueapp", "tra", "IANA: True BASIC");
		addEntry("TrueType Font", "application/x-font-ttf", "ttf", "Wikipedia: TrueType");
		addEntry("Turtle (Terse RDF Triple Language)", "text/turtle", "ttl", "Wikipedia: Turtle");
		addEntry("UMAJIN", "application/vnd.umajin", "umj", "IANA: UMAJIN");
		addEntry("Unique Object Markup Language", "application/vnd.uoml+xml", "uoml", "IANA: UOML");
		addEntry("Unity 3d", "application/vnd.unity", "unityweb", "IANA: Unity 3d");
		addEntry("Universal Forms Description Language", "application/vnd.ufdl", "ufd", "IANA: Universal Forms Description Language");
		addEntry("URI Resolution Services", "text/uri-list", "uri", "RFC 2483");
		addEntry("User Interface Quartz - Theme (Symbian)", "application/vnd.uiq.theme", "utz", "IANA: User Interface Quartz");
		addEntry("Ustar (Uniform Standard Tape Archive)", "application/x-ustar", "ustar", "Wikipedia: Ustar");
		addEntry("UUEncode", "text/x-uuencode", "uu", "Wikipedia: UUEncode");
		addEntry("vCalendar", "text/x-vcalendar", "vcs", "Wikipedia: vCalendar");
		addEntry("vCard", "text/x-vcard", "vcf", "Wikipedia: vCard");
		addEntry("Video CD", "application/x-cdlink", "vcd", "Wikipedia: Video CD");
		addEntry("Viewport+", "application/vnd.vsf", "vsf", "IANA: Viewport+");
		addEntry("Virtual Reality Modeling Language", "model/vrml", "wrl", "Wikipedia: VRML");
		addEntry("VirtualCatalog", "application/vnd.vcx", "vcx", "IANA: VirtualCatalog");
		addEntry("Virtue MTS", "model/vnd.mts", "mts", "IANA: MTS");
		addEntry("Virtue VTU", "model/vnd.vtu", "vtu", "IANA: VTU");
		addEntry("Visionary", "application/vnd.visionary", "vis", "IANA: Visionary");
		addEntry("Vivo", "video/vnd.vivo", "viv", "IANA: Vivo");
		addEntry("Voice Browser Call Control", "application/ccxml+xml,", "ccxml", "Voice Browser Call Control: CCXML Version 1.0");
		addEntry("VoiceXML", "application/voicexml+xml", "vxml", "RFC 4267");
		addEntry("WAIS Source", "application/x-wais-source", "src", "YoLinux");
		addEntry("WAP Binary XML (WBXML)", "application/vnd.wap.wbxml", "wbxml", "IANA: WBXML");
		addEntry("WAP Bitamp (WBMP)", "image/vnd.wap.wbmp", "wbmp", "IANA: WBMP");
		addEntry("Waveform Audio File Format (WAV)", "audio/x-wav", "wav", "Wikipedia: WAV");
		addEntry("Waveform Audio File Format (WAV)", "audio/wav", "wav", "Wikipedia: WAV");
		addEntry("Web Distributed Authoring and Versioning", "application/davmount+xml", "davmount", "RFC 4918");
		addEntry("Web Open Font Format", "application/x-font-woff", "woff", "Wikipedia: Web Open Font Format");
		addEntry("Web Services Policy", "application/wspolicy+xml", "wspolicy", "W3C Web Services Policy");
		addEntry("WebP Image", "image/webp", "webp", "Wikipedia: WebP");
		addEntry("WebTurbo", "application/vnd.webturbo", "wtb", "IANA: WebTurbo");
		addEntry("Widget Packaging and XML Configuration", "application/widget", "wgt", "W3C Widget Packaging and XML Configuration");
		addEntry("WinHelp", "application/winhlp", "hlp", "Wikipedia: WinHelp");
		addEntry("Wireless Markup Language (WML)", "text/vnd.wap.wml", "wml", "Wikipedia: WML");
		addEntry("Wireless Markup Language Script (WMLScript)", "text/vnd.wap.wmlscript", "wmls", "Wikipedia: WMLScript");
		addEntry("WMLScript", "application/vnd.wap.wmlscriptc", "wmlsc", "IANA: WMLScript");
		addEntry("Wordperfect", "application/vnd.wordperfect", "wpd", "IANA: Wordperfect");
		addEntry("Worldtalk", "application/vnd.wt.stf", "stf", "IANA: Worldtalk");
		addEntry("WSDL - Web Services Description Language", "application/wsdl+xml", "wsdl", "W3C Web Service Description Language");
		addEntry("X BitMap", "image/x-xbitmap", "xbm", "Wikipedia: X BitMap");
		addEntry("X PixMap", "image/x-xpixmap", "xpm", "Wikipedia: X PixMap");
		addEntry("X Window Dump", "image/x-xwindowdump", "xwd", "Wikipedia: X Window Dump");
		addEntry("X.509 Certificate", "application/x-x509-ca-cert", "der", "Wikipedia: X.509");
		addEntry("Xfig", "application/x-xfig", "fig", "Wikipedia: Xfig");
		addEntry("XHTML - The Extensible HyperText Markup Language", "application/xhtml+xml", "xhtml", "W3C XHTML");
		addEntry("XML - Extensible Markup Language", "application/xml", "xml", "W3C XML");
		addEntry("XML - Extensible Markup Language - Human Readable", "text/xml", "xml", "W3C XML");
		addEntry("XML Configuration Access Protocol - XCAP Diff", "application/xcap-diff+xml", "xdf", "Wikipedia: XCAP");
		addEntry("XML Encryption Syntax and Processing", "application/xenc+xml", "xenc", "W3C XML Encryption Syntax and Processing");
		addEntry("XML Patch Framework", "application/patch-ops-error+xml", "xer", "RFC 5261");
		addEntry("XML Resource Lists", "application/resource-lists+xml", "rl", "RFC 4826");
		addEntry("XML Resource Lists", "application/rls-services+xml", "rs", "RFC 4826");
		addEntry("XML Resource Lists Diff", "application/resource-lists-diff+xml", "rld", "RFC 4826");
		addEntry("XML Transformations", "application/xslt+xml", "xslt", "W3C XSLT");
		addEntry("XML-Binary Optimized Packaging", "application/xop+xml", "xop", "W3C XOP");
		addEntry("XPInstall - Mozilla", "application/x-xpinstall", "xpi", "Wikipedia: XPI");
		addEntry("XSPF - XML Shareable Playlist Format", "application/xspf+xml", "xspf", "XML Shareable Playlist Format");
		addEntry("XUL - XML User Interface Language", "application/vnd.mozilla.xul+xml", "xul", "IANA: XUL");
		addEntry("XYZ File Format", "chemical/x-xyz", "xyz", "Wikipedia: XYZ File Format");
		addEntry("YAML Ain't Markup Language / Yet Another Markup Language", "text/yaml", "yaml", "YAML: YAML Ain't Markup Language");
		addEntry("YANG Data Modeling Language", "application/yang", "yang", "Wikipedia: YANG");
		addEntry("YIN (YANG - XML)", "application/yin+xml", "yin", "Wikipedia: YANG");
		addEntry("Z.U.L. Geometry", "application/vnd.zul", "zir", "IANA: Z.U.L.");
		addEntry("Zip Archive", "application/zip", "zip", "Wikipedia: Zip");
		addEntry("ZVUE Media Manager", "application/vnd.handheld-entertainment+xml", "zmm", "IANA: ZVUE Media Manager");
		addEntry("Zzazz Deck", "application/vnd.zzazz.deck+xml", "zaz", "IANA: Zzazz");
    }

	private static void addEntry(String comment, String mimeType, String extension, String furtherComment) {
		biMap.put(mimeType, extension.split(", "));
    }

    public String getMimeTypeByExtension(String extension) {
        return String.valueOf(biMap.getKey(extension));
    }

	public String getExtensionByMimeType(String mimeType) {
		if (biMap.containsKey(mimeType)) {
			return ((String[]) biMap.get(mimeType))[0];
		}
		return null;
	}
    public String[] getExtensionsByMimeType(String mimeType) {
        return (String[]) biMap.get(mimeType);
    }

    @Synchronized
    public static MimeMapper getInstance() {
        if (instance == null) {
			instance = new MimeMapper();
		}
		return instance;
    }
}		