INSERT INTO GLOBALSETTINGS VALUES(1,'OpenMQ','localhost:7676','docShifter.queue','admin','admin','C:\DocShifter/work','C:\DocShifter/errorfolder');
INSERT INTO MODULE VALUES(1,'File system input module','com.docbyte.docshifter.sender.fs.scheduler.FSScheduler','Polls a file location and processes new files','Input',NULL);
INSERT INTO MODULE VALUES(2,'Documentum Sender','com.docbyte.docshifter.sender.dctm.scheduler.DCTMScheduler','Import module for Documentum','Input',NULL);
INSERT INTO MODULE VALUES(3,'Dropbox Sender','com.docbyte.docshifter.sender.dropbox.scheduler.DBScheduler','Polls a dropbox folder and processes new files','Input',NULL);
INSERT INTO MODULE VALUES(4,'Email Sender','com.docbyte.docshifter.sender.email.scheduler.EmailScheduler','Polls an e-mail inbox','Input',NULL);
INSERT INTO MODULE VALUES(5,'File System Export','com.docbyte.docshifter.receiver.operations.filesystem.FSExport','Export module for file system','Release',NULL);
INSERT INTO MODULE VALUES(6,'Documentum Export','com.docbyte.docshifter.receiver.operations.dctm.DCTMExport','Export module for Documentum','Release',NULL);
INSERT INTO MODULE VALUES(7,'All to PDF Transformation','com.docbyte.docshifter.receiver.operations.pdf.AllToPdfTransformation','Transformation to pdf','Transformation',NULL);
INSERT INTO MODULE VALUES(8,'Unzip Transformation','com.docbyte.docshifter.receiver.operations.unzip.Unzip','Extract zip file','Transformation',NULL);
INSERT INTO MODULE VALUES(9,'PdfAValidation','com.docbyte.docshifter.receiver.operations.aspose.PdfAValidation','Validation of pdf compliance.','Transformation',NULL);
INSERT INTO MODULE VALUES(10,'Words Transformation','com.docbyte.docshifter.receiver.operations.aspose.WordsTransformation','Transformation between word processor filetypes','Transformation',NULL);
INSERT INTO MODULE VALUES(11,'Cells Transformation','com.docbyte.docshifter.receiver.operations.aspose.CellsTransformation','Transformation between spreadsheet filetypes','Transformation',NULL);
INSERT INTO MODULE VALUES(12,'Slides Transformation','com.docbyte.docshifter.receiver.operations.aspose.SlidesTransformation','Transformation between presentation filetypes','Transformation',NULL);
INSERT INTO MODULE VALUES(13,'E-mail Transformation','com.docbyte.docshifter.receiver.operations.aspose.EmailTransformation','Transformation between e-mail filetypes','Transformation',NULL);
INSERT INTO MODULE VALUES(14,'Audio Transformation','com.docbyte.docshifter.receiver.operations.audio.AudioTransformation','Transformation between audio filetypes','Transformation',NULL);
INSERT INTO MODULE VALUES(15,'H264 Transformation','com.docbyte.docshifter.receiver.operations.video.h264Transformation','Transformation to h264 mp4 filetype','Transformation',NULL);
INSERT INTO MODULE VALUES(16,'WEBM Transformation','com.docbyte.docshifter.receiver.operations.video.webmTransformation','Transformation to webm filetype','Transformation',NULL);
INSERT INTO MODULE VALUES(17,'Png Transformation','com.docbyte.docshifter.receiver.operations.png.PngTransformation','Transformation to png filetype','Transformation',NULL);
INSERT INTO MODULE VALUES(18,'Thumbnail Transformation','com.docbyte.docshifter.receiver.operations.thumbnail.ThumbnailTransformation','Creation of png thumbnail for various video formats','Transformation',NULL);
INSERT INTO MODULE VALUES(19,'Email-processing','com.docbyte.docshifter.receiver.operations.preprocessing.EmlToXml','Converts e-mail files to xml-files','Transformation',NULL);
INSERT INTO MODULE VALUES(20,'Project Transformation','com.docbyte.docshifter.receiver.operations.aspose.ProjectTransformation','Transformation between Microsoft Task Project filetypes','Transformation',NULL);
INSERT INTO MODULE VALUES(21,'Diagram Transformation','com.docbyte.docshifter.receiver.operations.aspose.DiagramTransformation','Transformation between Microsoft Diagram filetypes','Transformation',NULL);
INSERT INTO MODULE VALUES(22,'Pdf Overlay Transformation','com.docbyte.docshifter.receiver.operations.aspose.PdfOverlayTransformation','Apply an overlay to PDF''s','Transformation',NULL);
INSERT INTO MODULE VALUES(23,'Merge Transformation','com.docbyte.docshifter.receiver.operations.aspose.MergeTransformation','Merges zip file with documents to one pdf file','Transformation',NULL);
INSERT INTO MODULE VALUES(24,'Doc Gen','com.docbyte.docshifter.receiver.operations.docgen.DocumentGenerator','Fills in mergefields of template with the taskdata','Transformation',NULL);
INSERT INTO MODULE VALUES(25,'PdfS Transformation','com.docbyte.docshifter.receiver.operations.aspose.PdfSTransformation','Apply security to PDF','Transformation',NULL);
INSERT INTO MODULE VALUES(26,'Sign Page','com.docbyte.docshifter.receiver.operations.signpage.SignPageCreator','Append sign page to pdf document','Transformation',NULL);
INSERT INTO MODULE VALUES(27,'OCR Transformation','com.docbyte.docshifter.receiver.operations.ocr.tocr.OCR','Perform Optical Character Recognition on document','Transformation',NULL);
INSERT INTO MODULE VALUES(28,'Index Rendition Transformation','com.docbyte.docshifter.receiver.operations.aspose.IndexTransformation','Transformation to an indexable text format','Transformation',NULL);
INSERT INTO MODULE VALUES(29,'PDF Optimization','com.docbyte.docshifter.receiver.operations.optimization.PDFOptimization','Optimize PDF document for web-based publication, data exchange or printing','Transformation',NULL);
INSERT INTO MODULE VALUES(30,'XML Read','com.docbyte.docshifter.receiver.operations.xml.XmlDataLoad','Read XML to taskdata','Transformation',NULL);
INSERT INTO MODULE VALUES(31,'Documentum New Rendition','com.docbyte.docshifter.receiver.operations.dctm.SaveOperation','Documentum release as new rendition(requires dctm input module)','Release',NULL);
INSERT INTO MODULEPARAMS VALUES(1,1);
INSERT INTO MODULEPARAMS VALUES(1,2);
INSERT INTO MODULEPARAMS VALUES(1,3);
INSERT INTO MODULEPARAMS VALUES(1,4);
INSERT INTO MODULEPARAMS VALUES(1,5);
INSERT INTO MODULEPARAMS VALUES(1,6);
INSERT INTO MODULEPARAMS VALUES(2,7);
INSERT INTO MODULEPARAMS VALUES(2,8);
INSERT INTO MODULEPARAMS VALUES(2,9);
INSERT INTO MODULEPARAMS VALUES(2,10);
INSERT INTO MODULEPARAMS VALUES(2,11);
INSERT INTO MODULEPARAMS VALUES(2,12);
INSERT INTO MODULEPARAMS VALUES(2,13);
INSERT INTO MODULEPARAMS VALUES(2,14);
INSERT INTO MODULEPARAMS VALUES(2,15);
INSERT INTO MODULEPARAMS VALUES(2,127);
INSERT INTO MODULEPARAMS VALUES(3,16);
INSERT INTO MODULEPARAMS VALUES(3,17);
INSERT INTO MODULEPARAMS VALUES(3,18);
INSERT INTO MODULEPARAMS VALUES(3,19);
INSERT INTO MODULEPARAMS VALUES(3,20);
INSERT INTO MODULEPARAMS VALUES(3,21);
INSERT INTO MODULEPARAMS VALUES(3,22);
INSERT INTO MODULEPARAMS VALUES(3,23);
INSERT INTO MODULEPARAMS VALUES(4,24);
INSERT INTO MODULEPARAMS VALUES(4,25);
INSERT INTO MODULEPARAMS VALUES(4,26);
INSERT INTO MODULEPARAMS VALUES(4,27);
INSERT INTO MODULEPARAMS VALUES(4,28);
INSERT INTO MODULEPARAMS VALUES(4,29);
INSERT INTO MODULEPARAMS VALUES(4,30);
INSERT INTO MODULEPARAMS VALUES(4,31);
INSERT INTO MODULEPARAMS VALUES(4,32);
INSERT INTO MODULEPARAMS VALUES(5,33);
INSERT INTO MODULEPARAMS VALUES(5,34);
INSERT INTO MODULEPARAMS VALUES(5,125);
INSERT INTO MODULEPARAMS VALUES(6,35);
INSERT INTO MODULEPARAMS VALUES(6,36);
INSERT INTO MODULEPARAMS VALUES(6,37);
INSERT INTO MODULEPARAMS VALUES(6,38);
INSERT INTO MODULEPARAMS VALUES(6,39);
INSERT INTO MODULEPARAMS VALUES(6,40);
INSERT INTO MODULEPARAMS VALUES(6,41);
INSERT INTO MODULEPARAMS VALUES(7,42);
INSERT INTO MODULEPARAMS VALUES(7,103);
INSERT INTO MODULEPARAMS VALUES(9,43);
INSERT INTO MODULEPARAMS VALUES(9,44);
INSERT INTO MODULEPARAMS VALUES(9,45);
INSERT INTO MODULEPARAMS VALUES(9,46);
INSERT INTO MODULEPARAMS VALUES(9,47);
INSERT INTO MODULEPARAMS VALUES(10,48);
INSERT INTO MODULEPARAMS VALUES(10,49);
INSERT INTO MODULEPARAMS VALUES(11,50);
INSERT INTO MODULEPARAMS VALUES(11,51);
INSERT INTO MODULEPARAMS VALUES(12,52);
INSERT INTO MODULEPARAMS VALUES(12,53);
INSERT INTO MODULEPARAMS VALUES(13,54);
INSERT INTO MODULEPARAMS VALUES(13,55);
INSERT INTO MODULEPARAMS VALUES(13,56);
INSERT INTO MODULEPARAMS VALUES(14,57);
INSERT INTO MODULEPARAMS VALUES(14,58);
INSERT INTO MODULEPARAMS VALUES(15,59);
INSERT INTO MODULEPARAMS VALUES(15,60);
INSERT INTO MODULEPARAMS VALUES(15,61);
INSERT INTO MODULEPARAMS VALUES(16,62);
INSERT INTO MODULEPARAMS VALUES(16,63);
INSERT INTO MODULEPARAMS VALUES(16,64);
INSERT INTO MODULEPARAMS VALUES(17,65);
INSERT INTO MODULEPARAMS VALUES(17,66);
INSERT INTO MODULEPARAMS VALUES(18,67);
INSERT INTO MODULEPARAMS VALUES(18,68);
INSERT INTO MODULEPARAMS VALUES(18,69);
INSERT INTO MODULEPARAMS VALUES(19,70);
INSERT INTO MODULEPARAMS VALUES(19,71);
INSERT INTO MODULEPARAMS VALUES(19,72);
INSERT INTO MODULEPARAMS VALUES(19,73);
INSERT INTO MODULEPARAMS VALUES(19,74);
INSERT INTO MODULEPARAMS VALUES(19,75);
INSERT INTO MODULEPARAMS VALUES(19,76);
INSERT INTO MODULEPARAMS VALUES(19,77);
INSERT INTO MODULEPARAMS VALUES(19,78);
INSERT INTO MODULEPARAMS VALUES(19,124);
INSERT INTO MODULEPARAMS VALUES(20,79);
INSERT INTO MODULEPARAMS VALUES(20,80);
INSERT INTO MODULEPARAMS VALUES(21,81);
INSERT INTO MODULEPARAMS VALUES(21,82);
INSERT INTO MODULEPARAMS VALUES(22,83);
INSERT INTO MODULEPARAMS VALUES(22,84);
INSERT INTO MODULEPARAMS VALUES(22,85);
INSERT INTO MODULEPARAMS VALUES(22,86);
INSERT INTO MODULEPARAMS VALUES(22,87);
INSERT INTO MODULEPARAMS VALUES(22,88);
INSERT INTO MODULEPARAMS VALUES(22,89);
INSERT INTO MODULEPARAMS VALUES(22,90);
INSERT INTO MODULEPARAMS VALUES(22,91);
INSERT INTO MODULEPARAMS VALUES(24,92);
INSERT INTO MODULEPARAMS VALUES(25,93);
INSERT INTO MODULEPARAMS VALUES(25,94);
INSERT INTO MODULEPARAMS VALUES(25,95);
INSERT INTO MODULEPARAMS VALUES(25,96);
INSERT INTO MODULEPARAMS VALUES(25,97);
INSERT INTO MODULEPARAMS VALUES(25,98);
INSERT INTO MODULEPARAMS VALUES(26,99);
INSERT INTO MODULEPARAMS VALUES(26,100);
INSERT INTO MODULEPARAMS VALUES(27,101);
INSERT INTO MODULEPARAMS VALUES(31,104);
INSERT INTO MODULEPARAMS VALUES(31,105);
INSERT INTO MODULEPARAMS VALUES(31,106);
INSERT INTO MODULEPARAMS VALUES(31,107);
INSERT INTO MODULEPARAMS VALUES(31,126);
INSERT INTO PARAM VALUES(1,'afterImportAction','What to do after import? Possible values are: delete/nothing/move','STRING',TRUE);
INSERT INTO PARAM VALUES(2,'start_date','Start date (format: 01/01/2000 00:00)','DATE',FALSE);
INSERT INTO PARAM VALUES(3,'location_path','Location path','STRING',TRUE);
INSERT INTO PARAM VALUES(4,'moveDestination_path','Will move the imported file to this location if afterImportAction is set to move','STRING',FALSE);
INSERT INTO PARAM VALUES(5,'end_date','End date (format: 01/01/2020 00:00)','DATE',FALSE);
INSERT INTO PARAM VALUES(6,'frequency','Frequency (every x seconds)','INTEGER',TRUE);
INSERT INTO PARAM VALUES(7,'start_date','Start date (format: 01/01/2000 00:00)','DATE',FALSE);
INSERT INTO PARAM VALUES(8,'dctm_user','Repository (technical) User','STRING',FALSE);
INSERT INTO PARAM VALUES(9,'renditionType','Type of the rendition (example: pdf, pdfa, pdfs, odf, html, ...)','STRING',FALSE);
INSERT INTO PARAM VALUES(10,'end_date','End date (format: 01/01/2020 00:00)','DATE',FALSE);
INSERT INTO PARAM VALUES(11,'dctm_repository','Repository','STRING',FALSE);
INSERT INTO PARAM VALUES(12,'dataFields','Attributes that need to be saved from dctm','STRING',FALSE);
INSERT INTO PARAM VALUES(13,'frequency','Frequency (every x seconds)','INTEGER',FALSE);
INSERT INTO PARAM VALUES(14,'relationName','Include all related documents by this relation name','STRING',FALSE);
INSERT INTO PARAM VALUES(15,'dctm_pass','Repository Password','PASSWORD',FALSE);
INSERT INTO PARAM VALUES(16,'afterImportAction','What to do after import? Possible values are: delete/nothing/move','STRING',FALSE);
INSERT INTO PARAM VALUES(17,'start_date','Start date (format: 01/01/2000 00:00)','DATE',FALSE);
INSERT INTO PARAM VALUES(18,'accessTokenKey','Access token key','STRING',FALSE);
INSERT INTO PARAM VALUES(19,'location_path','Path to your dropbox folder','STRING',FALSE);
INSERT INTO PARAM VALUES(20,'moveDestination_path','Will move the imported file to this location if afterImportAction is set to move','STRING',FALSE);
INSERT INTO PARAM VALUES(21,'end_date','End date (format: 01/01/2000 00:00)','DATE',FALSE);
INSERT INTO PARAM VALUES(22,'accessTokenSecret','Access token secret','PASSWORD',FALSE);
INSERT INTO PARAM VALUES(23,'frequency','Frequency (every x seconds)','INTEGER',FALSE);
INSERT INTO PARAM VALUES(24,'start_date','Start date (format: 01/01/2000 00:00)','DATE',FALSE);
INSERT INTO PARAM VALUES(25,'port','Port to connect to','INTEGER',FALSE);
INSERT INTO PARAM VALUES(26,'username','Username of your e-mail account','STRING',FALSE);
INSERT INTO PARAM VALUES(27,'protocol','Protocol to use for e-mail polling (POP3 or IMAP)','STRING',FALSE);
INSERT INTO PARAM VALUES(28,'end_date','End date (format: 01/01/2000 00:00)','DATE',FALSE);
INSERT INTO PARAM VALUES(29,'password','Password of your e-mail account','PASSWORD',FALSE);
INSERT INTO PARAM VALUES(30,'host','Host to connect to','STRING',FALSE);
INSERT INTO PARAM VALUES(31,'frequency','Frequency (every x seconds)','INTEGER',FALSE);
INSERT INTO PARAM VALUES(32,'notificationProperties','Path to notification properties file','STRING',TRUE);
INSERT INTO PARAM VALUES(33,'destinationfolder','Destination folder','STRING',TRUE);
INSERT INTO PARAM VALUES(34,'createFolders','Retain folder structure of input','BOOLEAN',FALSE);
INSERT INTO PARAM VALUES(35,'dctm_user','Repository (technical) User','STRING',FALSE);
INSERT INTO PARAM VALUES(36,'dctm_repository','Repository','STRING',FALSE);
INSERT INTO PARAM VALUES(37,'destfolder','Destination folderpath in the docbase','STRING',FALSE);
INSERT INTO PARAM VALUES(38,'foldertype','The target document folder type for the to be created folders','STRING',TRUE);
INSERT INTO PARAM VALUES(39,'objecttype','The target document object type','STRING',TRUE);
INSERT INTO PARAM VALUES(40,'createFolders','Create folders under the destination folder','BOOLEAN',TRUE);
INSERT INTO PARAM VALUES(41,'dctm_pass','Repository Password','PASSWORD',FALSE);
INSERT INTO PARAM VALUES(42,'pdfa','Convert to PDF/A compliant document (values: true/false)','BOOLEAN',FALSE);
INSERT INTO PARAM VALUES(43,'failOnInvalid','Fail processing on invalid document?','BOOLEAN',TRUE);
INSERT INTO PARAM VALUES(44,'detailed','Output a detailed log?','BOOLEAN',TRUE);
INSERT INTO PARAM VALUES(45,'format','The pdf version to validate against (PDF_A_1A, PDF_A_1B, PDF_A_2B, PDF_A_3B, PDF_X_1A, PDF_X_3, v_1_3, v_1_4, v_1_5, v_1_6, v_1_7)','STRING',TRUE);
INSERT INTO PARAM VALUES(46,'notificationProps','path to notification properties file','STRING',TRUE);
INSERT INTO PARAM VALUES(47,'logpath','The path where to log to','STRING',TRUE);
INSERT INTO PARAM VALUES(48,'pdfa','Convert to PDF/A compliant document (values: true/false)','BOOLEAN',FALSE);
INSERT INTO PARAM VALUES(49,'OutputFileType','Type to wich to convert the documents','STRING',TRUE);
INSERT INTO PARAM VALUES(50,'pdfa','Convert to PDF/A compliant document (values: true/false)','BOOLEAN',FALSE);
INSERT INTO PARAM VALUES(51,'OutputFileType','Type to wich to convert the documents','STRING',TRUE);
INSERT INTO PARAM VALUES(52,'pdfa','Convert to PDF/A compliant document (values: true/false)','BOOLEAN',FALSE);
INSERT INTO PARAM VALUES(53,'OutputFileType','Type to wich to convert the documents','STRING',TRUE);
INSERT INTO PARAM VALUES(54,'pdfa','Convert to PDF/A compliant document?','BOOLEAN',TRUE);
INSERT INTO PARAM VALUES(55,'OutputFileType','Type to wich to convert the documents','STRING',TRUE);
INSERT INTO PARAM VALUES(56,'embed_attachments_pdf','Convert the e-mail attachments?','BOOLEAN',TRUE);
INSERT INTO PARAM VALUES(57,'ffmpegPath','File system path to the ffmpeg executable','STRING',TRUE);
INSERT INTO PARAM VALUES(58,'OutputFileType','Type to wich to convert the documents','STRING',TRUE);
INSERT INTO PARAM VALUES(59,'Fps','Set output video frames per second','STRING',FALSE);
INSERT INTO PARAM VALUES(60,'ffmpegPath','File system path to the ffmpeg executable','STRING',TRUE);
INSERT INTO PARAM VALUES(61,'Resolution','Set output video resolution','STRING',FALSE);
INSERT INTO PARAM VALUES(62,'Fps','Set output video frames per second','STRING',FALSE);
INSERT INTO PARAM VALUES(63,'ffmpegPath','File system path to the ffmpeg executable','STRING',TRUE);
INSERT INTO PARAM VALUES(64,'Resolution','Set output video resolution','STRING',FALSE);
INSERT INTO PARAM VALUES(65,'MaxHeight','Maximum height of the png to output','INTEGER',TRUE);
INSERT INTO PARAM VALUES(66,'MaxWidth','Maximum width of the png to output','INTEGER',TRUE);
INSERT INTO PARAM VALUES(67,'MaxHeight','Maximum height of the png to output','INTEGER',TRUE);
INSERT INTO PARAM VALUES(68,'ffmpegPath','File system path to the ffmpeg executable','STRING',TRUE);
INSERT INTO PARAM VALUES(69,'MaxWidth','Maximum width of the png to output','INTEGER',TRUE);
INSERT INTO PARAM VALUES(70,'sendErrorMailWhenFault','Send error mail when detected non readable files? (values: true/false)','BOOLEAN',TRUE);
INSERT INTO PARAM VALUES(71,'only_eml','Only save the eml file as pdf (values: true/false)','BOOLEAN',FALSE);
INSERT INTO PARAM VALUES(72,'return_xml','Only create the xml file (values: true/false)','BOOLEAN',FALSE);
INSERT INTO PARAM VALUES(73,'output_extension','The extension of the created metadatafile','STRING',FALSE);
INSERT INTO PARAM VALUES(74,'zip','Save the output as zip (values: true/false)','BOOLEAN',FALSE);
INSERT INTO PARAM VALUES(75,'pdfa','Convert to PDF/A compliant document (values: true/false)','BOOLEAN',FALSE);
INSERT INTO PARAM VALUES(76,'processMailWhenFault','Continue the process when one or more files fails to convert? (values: true/false)','BOOLEAN',TRUE);
INSERT INTO PARAM VALUES(77,'notificationProps','path to notification properties file','STRING',TRUE);
INSERT INTO PARAM VALUES(78,'embed_attachments_pdf','Embed pdf of attachments in main pdf (values: true/false)','BOOLEAN',FALSE);
INSERT INTO PARAM VALUES(79,'pdfa','Convert to PDF/A compliant document (values: true/false)','BOOLEAN',FALSE);
INSERT INTO PARAM VALUES(80,'OutputFileType','Type to which to convert the documents','STRING',TRUE);
INSERT INTO PARAM VALUES(81,'pdfa','Convert to PDF/A compliant document with values: true/false','BOOLEAN',FALSE);
INSERT INTO PARAM VALUES(82,'OutputFileType','Type to which to convert the documents','STRING',TRUE);
INSERT INTO PARAM VALUES(83,'watermarkRotation','The rotation for the watermark. (for multiple watermarks at once seperate them by the delimiter specified in ''delimiter'')','STRING',TRUE);
INSERT INTO PARAM VALUES(84,'watermarkYPos','The Y-position for the watermark. (for multiple watermarks at once seperate them by the delimiter specified in ''delimiter'')','STRING',TRUE);
INSERT INTO PARAM VALUES(85,'watermarkText','The text that needs to be added. (for multiple watermarks at once seperate them by the delimiter specified in ''delimiter'')','STRING',TRUE);
INSERT INTO PARAM VALUES(86,'watermarkXPos','The X-position for the watermark. (for multiple watermarks at once seperate them by the delimiter specified in ''delimiter'')','STRING',TRUE);
INSERT INTO PARAM VALUES(87,'watermarkColor','The rotation for the watermark. (for multiple watermarks at once seperate them by the delimiter specified in ''delimiter'')','STRING',TRUE);
INSERT INTO PARAM VALUES(88,'delimiter','If file password enabled put the required password here','STRING',TRUE);
INSERT INTO PARAM VALUES(89,'pdfa','Convert to PDF/A compliant document (values: true/false)','BOOLEAN',FALSE);
INSERT INTO PARAM VALUES(90,'watermarkFont','The font for the watermark. (for multiple watermarks at once seperate them by the delimiter specified in ''delimiter'')','STRING',TRUE);
INSERT INTO PARAM VALUES(91,'watermarkFontsize','The font size for the watermark. (for multiple watermarks at once seperate them by the delimiter specified in ''delimiter'')','STRING',TRUE);
INSERT INTO PARAM VALUES(92,'template','Path to the template','STRING',TRUE);
INSERT INTO PARAM VALUES(93,'Changes','Modification rules: 0=No modifications allowed, 1=Modify Text Annotations, Empty/Other=Modification allowed','INTEGER',FALSE);
INSERT INTO PARAM VALUES(94,'OpenFilePassword','If file password enabled put the required password here','STRING',FALSE);
INSERT INTO PARAM VALUES(95,'EnableCopyingOfContent','True to enable copying of content','BOOLEAN',TRUE);
INSERT INTO PARAM VALUES(96,'Printing','Printing rules: 0=No printing allowed, 1=Allow printing in low quality Empty/Other=Allow printing','INTEGER',FALSE);
INSERT INTO PARAM VALUES(97,'UsePasswords','Apply passwords to the PDF. 1=Only passord for changing permissions, 2=Password for permissions and Opening of file','INTEGER',TRUE);
INSERT INTO PARAM VALUES(98,'PermissionPassword','Put the permissions password here','PASSWORD',TRUE);
INSERT INTO PARAM VALUES(99,'template','Sign page template document','STRING',TRUE);
INSERT INTO PARAM VALUES(100,'imageLocation','File system path of signature images','STRING',TRUE);
INSERT INTO PARAM VALUES(101,'extractPdf','Extract text pdf?','BOOLEAN',FALSE);
INSERT INTO PARAM VALUES(103,'embed_attachments_pdf','Embed attachements when converting mail files?','BOOLEAN',TRUE);
INSERT INTO PARAM VALUES(104,'dctm_update_type','How add the new content in documentum (rendition/primaryrendition/update/minor/major)','STRING',TRUE);
INSERT INTO PARAM VALUES(105,'dctm_user','Repository (technical) User','STRING',FALSE);
INSERT INTO PARAM VALUES(106,'dctm_repository','Repository','STRING',FALSE);
INSERT INTO PARAM VALUES(107,'dctm_pass','Repository Password','PASSWORD',FALSE);
INSERT INTO PARAM VALUES(123,'removeComments','Remove comments made in word documents?','BOOLEAN',FALSE);
INSERT INTO PARAM VALUES(124,'saveAsMsg','Save the mail as .msg format?','BOOLEAN',FALSE);
INSERT INTO PARAM VALUES(125,'WriteSettings','What to do when filename already exist: overwrite/discard/changename','STRING',TRUE);
INSERT INTO PARAM VALUES(126,'addExtension','Add extension to the filename?','BOOLEAN',FALSE);
INSERT INTO PARAM VALUES(127,'dctm_queue','Optional: get objects from another given queue','STRING',FALSE);
