/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nalpeiron_nalplibrary_NSA */

#ifndef _Included_com_nalpeiron_nalplibrary_NSA
#define _Included_com_nalpeiron_nalplibrary_NSA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nalpeiron_nalplibrary_NSA
 * Method:    NSAGetVersion
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSA_NSAGetVersion
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_nalpeiron_nalplibrary_NSA
 * Method:    NSAGetHostName
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSA_NSAGetHostName
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_nalpeiron_nalplibrary_NSA
 * Method:    NSALogin
 * Signature: (J[B[B[J)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSA_NSALogin
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jlongArray);

/*
 * Class:     com_nalpeiron_nalplibrary_NSA
 * Method:    NSALogout
 * Signature: (J[B[B[J)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSA_NSALogout
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jlongArray);

/*
 * Class:     com_nalpeiron_nalplibrary_NSA
 * Method:    NSAFeatureStart
 * Signature: (J[B[B[B[J)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSA_NSAFeatureStart
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jbyteArray, jlongArray);

/*
 * Class:     com_nalpeiron_nalplibrary_NSA
 * Method:    NSAFeatureStop
 * Signature: (J[B[B[B[J)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSA_NSAFeatureStop
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jbyteArray, jlongArray);

/*
 * Class:     com_nalpeiron_nalplibrary_NSA
 * Method:    NSAException
 * Signature: (J[B[B[B[B[J)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSA_NSAException
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jlongArray);

/*
 * Class:     com_nalpeiron_nalplibrary_NSA
 * Method:    NSASysInfo
 * Signature: (J[B[B[B[B[B[B[B[J)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSA_NSASysInfo
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jlongArray);

/*
 * Class:     com_nalpeiron_nalplibrary_NSA
 * Method:    NSASendCache
 * Signature: (J[B[J)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSA_NSASendCache
  (JNIEnv *, jobject, jlong, jbyteArray, jlongArray);

/*
 * Class:     com_nalpeiron_nalplibrary_NSA
 * Method:    NSAApStart
 * Signature: (J[B[B[J)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSA_NSAApStart
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jlongArray);

/*
 * Class:     com_nalpeiron_nalplibrary_NSA
 * Method:    NSAApStop
 * Signature: (J[B[B[J)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSA_NSAApStop
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jlongArray);

/*
 * Class:     com_nalpeiron_nalplibrary_NSA
 * Method:    NSAGetLocation
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSA_NSAGetLocation
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nalpeiron_nalplibrary_NSA
 * Method:    NSAGetPrivacy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSA_NSAGetPrivacy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nalpeiron_nalplibrary_NSA
 * Method:    NSASetPrivacy
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSA_NSASetPrivacy
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_nalpeiron_nalplibrary_NSA
 * Method:    NSAGetStats
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_nalpeiron_nalplibrary_NSA_NSAGetStats
  (JNIEnv *, jobject, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
